# Iristeau : 35571040606
# Lipapach : 27555660126

GAME_VERIFIED_MAPPING_BY_OBF: dict[str, str] = {
    # "gpl": "GameMessage",
    "hby": "SpellsEvent",  # 12728
    "hxv": "InventoryContentEvent",
    "jrp": "CharacterCharacteristicsEvent",
    "jtu": "CharacterSelectionEvent",  #
    "hzo": "InventoryWeightEvent",
    "gxh": "ZaapKnownListEvent",  # 191105026 (zaap astrub)
    "hxg": "JobExperiencesUpdateEvent",
    "jsc": "CharacterCharacteristicUpgradeRequest",
    "ior": "MapCurrentEvent",
    "ipl": "MapComplementaryInformationEvent",
    "ioh": "MapMovementRequest",
    "inw": "MapMovementEvent",
    "iof": "MapMovementConfirmRequest",
    "ipp": "MapMovementConfirmResponse",
    "ips": "MapChangeRequest",
    "iaa": "InteractiveUseRequest",
    "iah": "StatedElementUpdatedEvent",
    "iab": "InteractiveUsedEvent",
    "hrq": "NpcGenericActionRequest",
    "hrm": "NpcDialogQuestionEvent",
    "hrt": "NpcDialogReplyRequest",
    "jbn": "ExchangeStartedWithStorageEvent",  # 2147483647 (cest le max slot)
    "hzs": "StorageInventoryContentEvent",
    "jec": "ExchangeObjectTransferAllFromInventoryRequest",
    "izk": "ExchangeObjectMoveRequest",
    "hya": "ObjectAddedEvent",
    "hza": "ObjectQuantityEvent",
    "jcl": "ExchangeMoveKamaRequest",
    "jjh": "DialogLeaveRequest",
    "jdp": "ExchangeLeaveEvent",
    "icc": "HavenBagEnterRequest",
    "icb": "HavenBagExitRequest",
    "hzj": "ObjectUseRequest",
    "gxu": "TeleportRequest",
    # sale hotel
    "jbu": "ExchangeBidSellerStartedEvent",
    "jbv": "ExchangeBidHouseSearchRequest",
    "jdt": "ExchangeBidHousePriceRequest",
    "iyz": "ExchangeBidPriceEvent",
    "iyt": "ExchangeObjectMovePricedRequest",
    "jem": "ExchangeObjectModifyPricedRequest",
    "jcx": "ExchangeBidHouseItemAddedEvent",
    "jdu": "ExchangeBidHouseItemRemovedEvent",
    "klo": "TextInformationEvent",
    # # # # fight
    "hev": "AttackMonsterRequest",
    "iou": "FightMapInformationEvent",
    "iwv": "FightPlacementPossiblePositionsEvent",
    "iwu": "FightPlacementPositionRequest",
    "ixk": "FightReadyRequest",
    "iux": "FightTurnStartPlayingEvent",
    "iss": "GameActionFightEvent",
    "iqh": "GameActionFightCastRequest",
    "ita": "SequenceEndEvent",
    "iqg": "GameActionAcknowledgementRequest",
    "iwq": "FightLiveStateEvent",
    "ivo": "FightTurnFinishRequest",
    "jkz": "EntitiesDispositionEvent",
    "ivv": "FightRefreshCharacterStatsEvent",
    "ioi": "MapMovementRefusedEvent",
    "jrb": "ChatChannelMessageRequest",
    "jqu": "ChatPrivateMessageRequest",
    "jqy": "ChatChannelMessageEvent",
    "iia": "GuildMembershipEvent",  # Farm-Land
    "imj": "GuildChestCurrentListenersAddEvent",
    "jci": "ExchangeStartedWithMultiTabStorageEvent",
    "imq": "GuildChestTabSelectRequest",
    "jde": "ExchangeCraftStartedEvent",
    "jcn": "ExchangeSetCraftRecipeRequest",
    "jbl": "ExchangeCraftCountRequest",
    "jbj": "ExchangeCraftCountModifiedEvent",
    "jas": "ExchangeReadyRequest",
    "iak": "InteractiveUseErrorEvent",
}
GAME_MAPPING_FIELDS: dict[str, dict[str, str]] = {
    "GameMessage": {"request": "exuz", "event": "exvb", "response": "exva"},
    "InteractiveUseRequest": {"element_id": "fczk"},
    # "InteractiveElement": {"enabled_skills": "felr"},
    "GameActionFightEvent": {
        "slide": "ffun",
        "exchange_positions": "ffuq",
        "teleport_on_same_map": "ffus",
    },
}
