# Iristeau : 35571040606
# Lipapach : 27555660126

GAME_VERIFIED_MAPPING_BY_OBF: dict[str, str] = {
    # # "gpl": "GameMessage",
    "hbo": "SpellsEvent",  # 12728
    "hyp": "InventoryContentEvent",
    "jss": "CharacterCharacteristicsEvent",
    "jtn": "CharacterSelectionEvent",  #
    "hyx": "InventoryWeightEvent",
    "gya": "ZaapKnownListEvent",  # 191105026 (zaap astrub)
    "hwm": "JobExperiencesUpdateEvent",
    "ior": "MapCurrentEvent",
    "ipr": "MapComplementaryInformationEvent",
    "ipb": "MapMovementRequest",
    "ioy": "MapMovementEvent",
    "ipj": "MapMovementConfirmRequest",
    "ipl": "MapMovementConfirmResponse",
    "iqu": "MapChangeRequest",
    "iay": "InteractiveUseRequest",
    "ibf": "StatedElementUpdatedEvent",
    "ibh": "InteractiveUsedEvent",
    "hse": "NpcGenericActionRequest",
    "hrt": "NpcDialogQuestionEvent",
    "hrl": "NpcDialogReplyRequest",
    "jcr": "ExchangeStartedWithStorageEvent",  # 2147483647 (cest le max slot)
    "hzm": "StorageInventoryContentEvent",
    "jez": "ExchangeObjectTransferAllFromInventoryRequest",
    "jcq": "ExchangeObjectMoveRequest",
    "hxz": "ObjectAddedEvent",
    "hzw": "ObjectQuantityEvent",
    "jcp": "ExchangeMoveKamaRequest",
    "jkh": "DialogLeaveRequest",
    "jfl": "ExchangeLeaveEvent",
    "idb": "HavenBagEnterRequest",
    "iee": "HavenBagExitRequest",
    "iah": "ObjectUseRequest",
    "gxk": "TeleportRequest",
    # # sale hotel
    "jab": "ExchangeBidSellerStartedEvent",
    "jdy": "ExchangeBidHouseSearchRequest",
    "jcy": "ExchangeBidHousePriceRequest",
    "jbq": "ExchangeBidPriceEvent",
    "izk": "ExchangeObjectMovePricedRequest",
    "jdn": "ExchangeObjectModifyPricedRequest",
    "jeg": "ExchangeBidHouseItemRemovedEvent",
    "jfi": "ExchangeBidHouseItemAddedEvent",
    "kmi": "TextInformationEvent",
    # # # # # fight
    "hfs": "AttackMonsterRequest",
    "iqb": "FightMapInformationEvent",
    "iyy": "FightPlacementPossiblePositionsEvent",
    "iyl": "FightPlacementPositionRequest",
    "iyv": "FightReadyRequest",
    "ixq": "FightTurnStartPlayingEvent",
    "iuo": "GameActionFightCastRequest",
    "ity": "GameActionFightEvent",
    "ire": "SequenceEndEvent",
    "ird": "GameActionAcknowledgementRequest",
    "iwb": "FightLiveStateEvent",
    "ivm": "FightTurnFinishRequest",
    "jlr": "EntitiesDispositionEvent",
    "ivx": "FightRefreshCharacterStatsEvent",
    "ipx": "MapMovementRefusedEvent",
    "jrp": "ChatChannelMessageRequest",
    "jrl": "ChatPrivateMessageRequest",
    "jrm": "ChatChannelMessageEvent",
    "ijg": "GuildMembershipEvent",  # Farm-Land
    "ind": "GuildChestCurrentListenersAddEvent",
    "jdl": "ExchangeStartedWithMultiTabStorageEvent",
    "inf": "GuildChestTabSelectRequest",
    "jcu": "ExchangeCraftStartedEvent",  # 1 champs (le skill id)
    "jcn": "ExchangeSetCraftRecipeRequest",
    "izl": "ExchangeCraftCountRequest",
    "jbr": "ExchangeCraftCountModifiedEvent",
    "jfz": "ExchangeReadyRequest",
    "iba": "InteractiveUseErrorEvent",
}
GAME_MAPPING_FIELDS: dict[str, dict[str, str]] = {
    # "GameMessage": {"request": "exuz", "event": "exvb", "response": "exva"},
    "InteractiveUseRequest": {"element_id": "fdlu"},
    # # "InteractiveElement": {"enabled_skills": "felr"},
    "GameActionFightEvent": {
        "slide": "fgjg",
        "exchange_positions": "fgkn",
        # "teleport_on_same_map": "ffus",
    },
}
