# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apperance_fill.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'apperance_fill.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61pperance_fill.proto\x12\x33\x63om.ankama.dofus.server.game.protocol.cosmetic_fill\",\n\x1c\x43haracterFillSlotFaceRequest\x12\x0c\n\x04\x66\x61\x63\x65\x18\x01 \x01(\x05\"\xb9\x02\n\x1d\x43haracterFillSlotFaceResponse\x12m\n\x07success\x18\x01 \x01(\x0b\x32Z.com.ankama.dofus.server.game.protocol.cosmetic_fill.CharacterFillSlotFaceResponse.SuccessH\x00\x12i\n\x05\x65rror\x18\x02 \x01(\x0b\x32X.com.ankama.dofus.server.game.protocol.cosmetic_fill.CharacterFillSlotFaceResponse.ErrorH\x00\x1a+\n\x07Success\x12\x0e\n\x06\x66\x61\x63\x65Id\x18\x01 \x01(\x05\x12\x10\n\x08position\x18\x02 \x01(\x05\x1a\x07\n\x05\x45rrorB\x08\n\x06Result\"0\n\x1e\x43haracterFillSlotColorsRequest\x12\x0e\n\x06\x63olors\x18\x01 \x03(\x05\"\xbf\x02\n\x1f\x43haracterFillSlotColorsResponse\x12o\n\x07success\x18\x01 \x01(\x0b\x32\\.com.ankama.dofus.server.game.protocol.cosmetic_fill.CharacterFillSlotColorsResponse.SuccessH\x00\x12k\n\x05\x65rror\x18\x02 \x01(\x0b\x32Z.com.ankama.dofus.server.game.protocol.cosmetic_fill.CharacterFillSlotColorsResponse.ErrorH\x00\x1a+\n\x07Success\x12\x0e\n\x06\x63olors\x18\x01 \x03(\x05\x12\x10\n\x08position\x18\x02 \x01(\x05\x1a\x07\n\x05\x45rrorB\x08\n\x06Resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apperance_fill_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHARACTERFILLSLOTFACEREQUEST']._serialized_start=77
  _globals['_CHARACTERFILLSLOTFACEREQUEST']._serialized_end=121
  _globals['_CHARACTERFILLSLOTFACERESPONSE']._serialized_start=124
  _globals['_CHARACTERFILLSLOTFACERESPONSE']._serialized_end=437
  _globals['_CHARACTERFILLSLOTFACERESPONSE_SUCCESS']._serialized_start=375
  _globals['_CHARACTERFILLSLOTFACERESPONSE_SUCCESS']._serialized_end=418
  _globals['_CHARACTERFILLSLOTFACERESPONSE_ERROR']._serialized_start=420
  _globals['_CHARACTERFILLSLOTFACERESPONSE_ERROR']._serialized_end=427
  _globals['_CHARACTERFILLSLOTCOLORSREQUEST']._serialized_start=439
  _globals['_CHARACTERFILLSLOTCOLORSREQUEST']._serialized_end=487
  _globals['_CHARACTERFILLSLOTCOLORSRESPONSE']._serialized_start=490
  _globals['_CHARACTERFILLSLOTCOLORSRESPONSE']._serialized_end=809
  _globals['_CHARACTERFILLSLOTCOLORSRESPONSE_SUCCESS']._serialized_start=747
  _globals['_CHARACTERFILLSLOTCOLORSRESPONSE_SUCCESS']._serialized_end=790
  _globals['_CHARACTERFILLSLOTCOLORSRESPONSE_ERROR']._serialized_start=420
  _globals['_CHARACTERFILLSLOTCOLORSRESPONSE_ERROR']._serialized_end=427
# @@protoc_insertion_point(module_scope)
