syntax = "proto3";

package com.ankama.dofus.server.game.protocol.cosmetic_fill;

message CharacterFillSlotFaceRequest {
	int32 face = 1;
}

message CharacterFillSlotFaceResponse {
	oneof Result {
		.com.ankama.dofus.server.game.protocol.cosmetic_fill.CharacterFillSlotFaceResponse.Success success = 1;
		.com.ankama.dofus.server.game.protocol.cosmetic_fill.CharacterFillSlotFaceResponse.Error error = 2;
	}
	message Success {
		int32 faceId = 1;
		int32 position = 2;
	}

	message Error {
	}

}

message CharacterFillSlotColorsRequest {
	repeated int32 colors = 1;
}

message CharacterFillSlotColorsResponse {
	oneof Result {
		.com.ankama.dofus.server.game.protocol.cosmetic_fill.CharacterFillSlotColorsResponse.Success success = 1;
		.com.ankama.dofus.server.game.protocol.cosmetic_fill.CharacterFillSlotColorsResponse.Error error = 2;
	}
	message Success {
		repeated int32 colors = 1;
		int32 position = 2;
	}

	message Error {
	}

}