# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rule.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'rule.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrule.proto\x12*com.ankama.dofus.server.game.protocol.rule\x1a\x0c\x63ommon.proto\"\xad\x01\n\x1b\x43haracterUpdateBreedRequest\x12\x10\n\x08\x62reed_id\x18\x01 \x01(\x05\x12\x44\n\x06gender\x18\x02 \x01(\x0e\x32\x34.com.ankama.dofus.server.game.protocol.common.Gender\x12\x0e\n\x06\x63olors\x18\x03 \x03(\x05\x12\x13\n\x0b\x63osmetic_id\x18\x04 \x01(\x05\x12\x11\n\tobject_id\x18\x05 \x01(\t*\xfd\x02\n\x0eNameCompliance\x12\x0b\n\x07NAME_OK\x10\x00\x12\"\n\x1eNAME_ERROR_SERVICE_UNAVAILABLE\x10\x01\x12\x1d\n\x19NAME_ERROR_ALREADY_EXISTS\x10\x02\x12\x1b\n\x17NAME_ERROR_BAD_ALPHABET\x10\x03\x12\x19\n\x15NAME_ERROR_BAD_LENGTH\x10\x04\x12\x17\n\x13NAME_ERROR_BAD_CHAR\x10\x05\x12$\n NAME_ERROR_INVALID_DASH_POSITION\x10\x06\x12!\n\x1dNAME_ERROR_NAME_WITH_BAD_CASE\x10\x07\x12-\n)NAME_ERROR_TOO_MANY_CONSECUTIVE_IDENTICAL\x10\x08\x12\x1f\n\x1bNAME_ERROR_TOO_MANY_SPECIAL\x10\t\x12\x18\n\x14NAME_ERROR_FORBIDDEN\x10\n\x12\x17\n\x13NAME_ERROR_RESERVED\x10\x0b\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rule_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAMECOMPLIANCE']._serialized_start=249
  _globals['_NAMECOMPLIANCE']._serialized_end=630
  _globals['_CHARACTERUPDATEBREEDREQUEST']._serialized_start=73
  _globals['_CHARACTERUPDATEBREEDREQUEST']._serialized_end=246
# @@protoc_insertion_point(module_scope)
