syntax = "proto3";

package com.ankama.dofus.server.game.protocol.rule;

import "common.proto";


enum NameCompliance {
  NAME_OK = 0;
  NAME_ERROR_SERVICE_UNAVAILABLE = 1;
  NAME_ERROR_ALREADY_EXISTS = 2;
  NAME_ERROR_BAD_ALPHABET = 3;
  NAME_ERROR_BAD_LENGTH = 4;
  NAME_ERROR_BAD_CHAR = 5;
  NAME_ERROR_INVALID_DASH_POSITION = 6;
  NAME_ERROR_NAME_WITH_BAD_CASE = 7;
  NAME_ERROR_TOO_MANY_CONSECUTIVE_IDENTICAL = 8;
  NAME_ERROR_TOO_MANY_SPECIAL = 9;
  NAME_ERROR_FORBIDDEN = 10;
  NAME_ERROR_RESERVED = 11;
}

message CharacterUpdateBreedRequest {
	int32 breed_id = 1;
	.com.ankama.dofus.server.game.protocol.common.Gender gender = 2;
	repeated int32 colors = 3;
	int32 cosmetic_id = 4;
	string object_id = 5;
}