from typing import Any

from PyQt6.QtCore import QRect
from PyQt6.QtGui import QColor
from PyQt6.QtWidgets import QWidget

class AcrylicBrush:
    tintColor: QColor
    luminosityColor: QColor
    def __init__(self, parent: QWidget, radius: int = 0) -> None: ...
    def isAvailable(self) -> bool: ...
    def grabImage(self, rect: QRect) -> None: ...
    def setClipPath(self, path: Any) -> None: ...
    def paint(self) -> None: ...
