from enum import Enum
from typing import Any

from PyQt6.QtCore import QPoint, QRect, QSize
from PyQt6.QtWidgets import QLayout, QWidget

class FlyoutAnimationType(Enum):
    PULL_UP = 0
    PUSH_UP = 1
    SLIDE_LEFT = 2
    SLIDE_RIGHT = 3
    NONE = 4
    DROP_DOWN = 5

class FlyoutViewBase(QWidget):
    def __init__(self, parent: QWidget | None = None) -> None: ...

class AcrylicFlyoutViewBase(FlyoutViewBase): ...

class FlyoutAnimationManager:
    def position(self, target: QWidget) -> QPoint: ...

class SlideRightFlyoutAnimationManager(FlyoutAnimationManager):
    def __init__(self, flyout: Any) -> None: ...

class Flyout(QWidget):
    aniManager: FlyoutAnimationManager
    view: FlyoutViewBase
    def __init__(self, view: FlyoutViewBase, parent: QWidget | None = None) -> None: ...
    def exec(
        self, pos: QPoint, aniType: FlyoutAnimationType = FlyoutAnimationType.PULL_UP
    ) -> None: ...
    def resize(self, *args: Any) -> None: ...
    def sizeHint(self) -> QSize: ...
    def setFixedSize(self, *args: Any) -> None: ...
    def layout(self) -> QLayout | None: ...
    def move(self, *args: Any) -> None: ...
    def geometry(self) -> QRect: ...
