[mypy]
python_version = 3.12

[mypy-*.common_pb2]
ignore_missing_imports = true

[mypy-*.pb2]
ignore_missing_imports = true

[mypy-qfluentwidgets.*]
ignore_missing_imports = true

[mypy-ankama_launcher_emulator.*]
ignore_missing_imports = true

[mypy-d3_mapping.resources.protos.*]
ignore_missing_imports = true
