[tool.poetry]
name = "bot_dofus_unity"
version = "0.1.0"
description = ""
authors = ["Valentin Alix <valentin-alix.850@outlook.fr>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">3.11,<3.14"
pydantic = ">2.8"
scapy = "^2.5.0"
psutil = "^6.0.0"
pyqt5-qt5 = "5.15.2"
pyqt5 = "5.15.10"
pyqt-fluent-widgets = { extras = ["full"], version = "^1.6.3" }
ankama-launcher-emulator = { git = "https://github.com/Valentin-alix/AnkamaLauncherEmulator" }
cachetools = "^5.5.0"
msgspec = "^0.18.6"
protobuf = "5.28.3"
sortedcontainers = "^2.4.0"
pywin32 = "^308"
pywin32-stubs = "^1.0.7"

[tool.poetry.group.dev.dependencies]
pyqt5-stubs = "^5.15.6.0"
types-cachetools = "^5.5.0.20240820"
tqdm = "^4.66.5"
gprof2dot = "^2024.6.6"
line-profiler-pycharm = "^1.2.0"
icecream = "^2.1.3"
pyinstaller = "^6.11.1"
ruff = "^0.9.4"

[tool.pylint]
disable = [
    "missing-docstring", "R0902", "too-few-public-methods"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"