from collections.abc import Callable

class Job:
    @property
    def second(self) -> Job: ...
    @property
    def seconds(self) -> Job: ...
    @property
    def minute(self) -> Job: ...
    @property
    def minutes(self) -> Job: ...
    @property
    def hour(self) -> Job: ...
    @property
    def hours(self) -> Job: ...
    @property
    def day(self) -> Job: ...
    @property
    def monday(self) -> Job: ...
    @property
    def tuesday(self) -> Job: ...
    @property
    def wednesday(self) -> Job: ...
    @property
    def thursday(self) -> Job: ...
    @property
    def friday(self) -> Job: ...
    @property
    def saturday(self) -> Job: ...
    @property
    def sunday(self) -> Job: ...
    def at(self, time_str: str) -> Job: ...
    def do(
        self, job_func: Callable[[], object], *args: object, **kwargs: object
    ) -> Job: ...

def every(interval: int = 1) -> Job: ...
def run_pending() -> None: ...
def cancel_job(job: Job) -> None: ...
def clear() -> None: ...
