// Decompiled with protodec

syntax = "proto3";

import "google/protobuf/any.proto";

enum lcg {
  LCG_ETKY = 0;
  LCG_ETKZ = 1;
  LCG_ETLA = 2;
  LCG_ETLB = 3;
  LCG_ETLC = 4;
  LCG_ETLD = 5;
  LCG_ETLE = 6;
}

message lci {
  oneof fpts {
    lck fptp = 1;
    lcm fptq = 2;
    lco fptr = 3;
  }
}

message lck {
  string fptw = 1;
  oneof fpue {
    lcp fptx = 2;
    lct fpty = 3;
    ldh fptz = 4;
    ldw fpua = 5;
    leb fpub = 6;
    leg fpuc = 7;
    leo fpud = 8;
  }
}

message lcm {
  string fpui = 1;
  oneof fpup {
    lcq fpuj = 2;
    ldg fpuk = 3;
    ldm fpul = 4;
    ldy fpum = 5;
    len fpun = 6;
    lev fpuo = 7;
  }
}

message lco {
  oneof fpuu {
    lcr fput = 1;
  }
}

message lcp {
}

message lcq {
}

message lcr {
  lds fpve = 1;
}

message lct {
  string fpvi = 1;
  string fpvl = 5;
  oneof fpvm {
    lcw fpvj = 3;
    lcx fpvk = 4;
  }
}

message lcw {
  string fpvv = 1;
  lcu fpvw = 2;
  message lcu {
    int64 fpvq = 1;
    string fpvr = 2;
  }
}

message lcx {
  string fpwa = 1;
}

message ldg {
  oneof fpxi {
    ldb fpxg = 1;
    lde fpxh = 2;
  }
  message ldb {
    int64 fpwl = 1;
    string fpwm = 2;
    string fpwn = 3;
    ldp fpwo = 4;
    string fpwp = 5;
    lcz fpwq = 6;
    optional int32 fpwr = 7;
    ldz fpwt = 8;
    lew fpwu = 9;
    message lcz {
      bool fpwe = 1;
      bool fpwf = 2;
      bool fpwg = 3;
      bool fpwh = 4;
    }
  }
  message lde {
    ldc fpwy = 1;
    optional string fpwz = 2;
    optional string fpxb = 3;
    enum ldc {
      LDC_ETQF = 0;
      LDC_ETQG = 1;
      LDC_ETQH = 2;
      LDC_ETQI = 3;
      LDC_ETQJ = 4;
      LDC_ETQK = 5;
      LDC_ETQL = 6;
      LDC_ETQM = 7;
      LDC_ETQN = 8;
      LDC_ETQO = 9;
      LDC_ETQP = 10;
      LDC_ETQQ = 11;
      LDC_ETQR = 12;
      LDC_ETQS = 13;
      LDC_ETQT = 14;
    }
  }
}

message ldh {
  int32 fpxm = 1;
}

message ldm {
  oneof fpxz {
    ldk fpxw = 1;
    ldj fpxx = 2;
  }
  message ldk {
    string fpxq = 1;
    string fpxr = 2;
    repeated int32 fpxs = 3;
  }
  enum ldj {
    LDJ_ETRR = 0;
    LDJ_ETRS = 1;
    LDJ_ETRT = 2;
    LDJ_ETRU = 3;
  }
}

message ldp {
  repeated lds fpyi = 1;
  repeated ldn fpyj = 2;
  bool fpyk = 3;
  message ldn {
    lcg fpyd = 1;
    int32 fpye = 2;
  }
}

message lds {
  ldv fpyo = 1;
  ldq fpyp = 2;
  repeated lef fpyq = 3;
  enum ldq {
    LDQ_ETTA = 0;
    LDQ_ETTB = 1;
    LDQ_ETTC = 2;
    LDQ_ETTD = 3;
  }
}

message ldv {
  int32 fpyu = 1;
  ldt fpyv = 2;
  lcg fpyw = 3;
  enum ldt {
    LDT_ETTN = 0;
    LDT_ETTO = 1;
  }
}

message ldw {
  int64 fpza = 1;
}

message ldy {
  oneof fpzg {
    ldz fpze = 2;
    lea fpzf = 3;
  }
}

message ldz {
  bool fpzk = 1;
  int64 fpzl = 2;
  string fpzm = 3;
  string fpzn = 4;
  ldp fpzo = 5;
}

message lea {
}

message leb {
}

message lef {
  string fpzy = 1;
  led fpzz = 2;
  lec fqaa = 3;
  int32 fqab = 4;
  string fqac = 5;
  enum led {
    LED_ETVC = 0;
    LED_ETVD = 1;
    LED_ETVE = 2;
    LED_ETVF = 3;
    LED_ETVG = 4;
    LED_ETVH = 5;
    LED_ETVI = 6;
    LED_ETVJ = 7;
    LED_ETVK = 8;
    LED_ETVL = 9;
    LED_ETVM = 10;
    LED_ETVN = 11;
    LED_ETVO = 12;
    LED_ETVP = 13;
    LED_ETVQ = 14;
    LED_ETVR = 15;
    LED_ETVS = 16;
    LED_ETVT = 17;
    LED_ETVU = 18;
  }
  enum lec {
    LEC_ETVA = 0;
    LEC_ETVB = 1;
  }
}

message leg {
}

message len {
  oneof fqaw {
    lel fqat = 1;
    lei fqau = 2;
  }
  message lel {
    repeated lej fqap = 1;
    message lej {
      string fqaj = 1;
      string fqak = 2;
      repeated int32 fqal = 3;
    }
  }
  enum lei {
    LEI_ETWM = 0;
    LEI_ETWN = 1;
  }
}

message leo {
  string fqba = 1;
  string fqbb = 2;
}

message lev {
  oneof fqbp {
    leq fqbn = 1;
    let fqbo = 2;
  }
  message leq {
    repeated int32 fqbf = 1;
  }
  message let {
    ler fqbj = 1;
    enum ler {
      LER_ETXW = 0;
      LER_ETXX = 1;
      LER_ETXY = 2;
      LER_ETXZ = 3;
    }
  }
}

message lew {
  string fqbt = 1;
  string fqbu = 2;
  repeated int32 fqbv = 3;
}

