// Decompiled with protodec

syntax = "proto3";

import "google/protobuf/any.proto";

enum kgr {
  KGR_DVXB = 0;
  KGR_DVXC = 1;
  KGR_DVXD = 2;
  KGR_DVXE = 3;
  KGR_DVXF = 4;
  KGR_DVXG = 5;
  KGR_DVXH = 6;
}

message kgt {
  oneof emyx {
    kgv emyu = 1;
    kgx emyv = 2;
    kgz emyw = 3;
  }
}

message kgv {
  string emzb = 1;
  oneof emzj {
    kha emzc = 2;
    khe emzd = 3;
    khs emze = 4;
    kih emzf = 5;
    kim emzg = 6;
    kir emzh = 7;
    kiz emzi = 8;
  }
}

message kgx {
  string emzn = 1;
  oneof emzu {
    khb emzo = 2;
    khr emzp = 3;
    khx emzq = 4;
    kij emzr = 5;
    kiy emzs = 6;
    kjg emzt = 7;
  }
}

message kgz {
  oneof emzz {
    khc emzy = 1;
  }
}

message kha {
}

message khb {
}

message khc {
  kid enaj = 1;
}

message khe {
  string enan = 1;
  string enaq = 5;
  oneof enar {
    khh enao = 3;
    khi enap = 4;
  }
}

message khh {
  string enba = 1;
  khf enbb = 2;
  message khf {
    int64 enav = 1;
    string enaw = 2;
  }
}

message khi {
  string enbf = 1;
}

message khr {
  oneof enco {
    khm encm = 1;
    khp encn = 2;
  }
  message khm {
    int64 enbs = 1;
    string enbt = 2;
    string enbu = 3;
    kia enbv = 4;
    string enbw = 5;
    khk enbx = 6;
    optional int32 enby = 7;
    kik enca = 8;
    message khk {
      bool enbj = 1;
      bool enbk = 2;
      bool enbl = 3;
      bool enbm = 4;
      bool enbn = 5;
      bool enbo = 6;
    }
  }
  message khp {
    khn ence = 1;
    optional string encf = 2;
    optional string ench = 3;
    enum khn {
      KHN_DWCK = 0;
      KHN_DWCL = 1;
      KHN_DWCM = 2;
      KHN_DWCN = 3;
      KHN_DWCO = 4;
      KHN_DWCP = 5;
      KHN_DWCQ = 6;
      KHN_DWCR = 7;
      KHN_DWCS = 8;
      KHN_DWCT = 9;
      KHN_DWCU = 10;
      KHN_DWCV = 11;
      KHN_DWCW = 12;
      KHN_DWCX = 13;
    }
  }
}

message khs {
  int32 encs = 1;
}

message khx {
  oneof endf {
    khv endc = 1;
    khu endd = 2;
  }
  message khv {
    string encw = 1;
    string encx = 2;
    repeated int32 ency = 3;
  }
  enum khu {
    KHU_DWDV = 0;
    KHU_DWDW = 1;
    KHU_DWDX = 2;
    KHU_DWDY = 3;
  }
}

message kia {
  repeated kid endo = 1;
  repeated khy endp = 2;
  bool endq = 3;
  message khy {
    kgr endj = 1;
    int32 endk = 2;
  }
}

message kid {
  kig endu = 1;
  kib endv = 2;
  repeated kiq endw = 3;
  enum kib {
    KIB_DWFE = 0;
    KIB_DWFF = 1;
    KIB_DWFG = 2;
    KIB_DWFH = 3;
  }
}

message kig {
  int32 enea = 1;
  kie eneb = 2;
  kgr enec = 3;
  enum kie {
    KIE_DWFR = 0;
    KIE_DWFS = 1;
  }
}

message kih {
  int64 eneg = 1;
}

message kij {
  oneof enem {
    kik enek = 2;
    kil enel = 3;
  }
}

message kik {
  bool eneq = 1;
  int64 ener = 2;
  string enes = 3;
  string enet = 4;
  kia eneu = 5;
}

message kil {
}

message kim {
}

message kiq {
  string enfe = 1;
  kio enff = 2;
  kin enfg = 3;
  int32 enfh = 4;
  string enfi = 5;
  enum kio {
    KIO_DWHG = 0;
    KIO_DWHH = 1;
    KIO_DWHI = 2;
    KIO_DWHJ = 3;
    KIO_DWHK = 4;
    KIO_DWHL = 5;
    KIO_DWHM = 6;
    KIO_DWHN = 7;
    KIO_DWHO = 8;
    KIO_DWHP = 9;
    KIO_DWHQ = 10;
    KIO_DWHR = 11;
    KIO_DWHS = 12;
    KIO_DWHT = 13;
    KIO_DWHU = 14;
    KIO_DWHV = 15;
    KIO_DWHW = 16;
    KIO_DWHX = 17;
    KIO_DWHY = 18;
  }
  enum kin {
    KIN_DWHE = 0;
    KIN_DWHF = 1;
  }
}

message kir {
}

message kiy {
  oneof engc {
    kiw enfz = 1;
    kit enga = 2;
  }
  message kiw {
    repeated kiu enfv = 1;
    message kiu {
      string enfp = 1;
      string enfq = 2;
      repeated int32 enfr = 3;
    }
  }
  enum kit {
    KIT_DWIQ = 0;
    KIT_DWIR = 1;
  }
}

message kiz {
  string engg = 1;
  string engh = 2;
}

message kjg {
  oneof engv {
    kjb engt = 1;
    kje engu = 2;
  }
  message kjb {
    repeated int32 engl = 1;
  }
  message kje {
    kjc engp = 1;
    enum kjc {
      KJC_DWKA = 0;
      KJC_DWKB = 1;
      KJC_DWKC = 2;
      KJC_DWKD = 3;
    }
  }
}

