// Decompiled with protodec

syntax = "proto3";

message leg {
  lei frcz = 1;
  lek frda = 2;
  lem frdb = 3;
}

message lei {
  string frdg = 1;
  len frdh = 2;
  ler frdi = 3;
  lff frdj = 4;
  lfu frdk = 5;
  lfz frdl = 6;
  lge frdm = 7;
  lgm frdn = 8;
}

message len {
}

message ler {
  string fret = 1;
  leu freu = 3;
  lev frev = 4;
  string frew = 5;
}

message leu {
  string frfg = 1;
  les frfh = 2;
  message les {
    int64 frfb = 1;
    string frfc = 2;
  }
}

message lev {
  string frfl = 1;
}

message lff {
  int32 frgx = 1;
}

message lfu {
  int64 fril = 1;
}

message lfz {
}

message lge {
}

message lgm {
  string frkl = 1;
  string frkm = 2;
}

message lek {
  string frds = 1;
  leo frdt = 2;
  lfe frdu = 3;
  lfk frdv = 4;
  lfw frdw = 5;
  lgl frdx = 6;
  lgt frdy = 7;
}

message leo {
}

message lfe {
  lez frgr = 1;
  lfc frgs = 2;
  message lez {
    int64 frfw = 1;
    string frfx = 2;
    string frfy = 3;
    lfn frfz = 4;
    string frga = 5;
    lex frgb = 6;
    optional int32 frgc = 7;
    lfx frge = 8;
    lgu frgf = 9;
    message lex {
      bool frfp = 1;
      bool frfq = 2;
      bool frfr = 3;
      bool frfs = 4;
    }
  }
  message lfc {
    lfa frgj = 1;
    optional string frgk = 2;
    optional string frgm = 3;
    message lfa {
    }
  }
}

message lfn {
  repeated lfq frht = 1;
  repeated lfl frhu = 2;
  bool frhv = 3;
  message lfl {
    lee frho = 1;
    int32 frhp = 2;
  }
}

message lfq {
  lft frhz = 1;
  lfo fria = 2;
  repeated lgd frib = 3;
  message lfo {
  }
}

message lft {
  int32 frif = 1;
  lfr frig = 2;
  lee frih = 3;
  message lfr {
  }
}

message lee {
}

message lgd {
  string frjj = 1;
  lgb frjk = 2;
  lga frjl = 3;
  int32 frjm = 4;
  string frjn = 5;
  message lgb {
  }
  message lga {
  }
}

message lfx {
  bool friv = 1;
  int64 friw = 2;
  string frix = 3;
  string friy = 4;
  lfn friz = 5;
}

message lgu {
  string frle = 1;
  string frlf = 2;
  repeated int32 frlg = 3;
}

message lfk {
  lfi frhh = 1;
  optional lfh frhi = 2;
  message lfi {
    string frhb = 1;
    string frhc = 2;
    repeated int32 frhd = 3;
  }
  message lfh {
  }
}

message lfw {
  lfx frip = 2;
  lfy friq = 3;
}

message lfy {
}

message lgl {
  lgj frke = 1;
  optional lgg frkf = 2;
  message lgj {
    repeated lgh frka = 1;
    message lgh {
      string frju = 1;
      string frjv = 2;
      repeated int32 frjw = 3;
    }
  }
  message lgg {
  }
}

message lgt {
  lgo frky = 1;
  lgr frkz = 2;
  message lgo {
    repeated int32 frkq = 1;
  }
  message lgr {
    lgp frku = 1;
    message lgp {
    }
  }
}

message lem {
  lep fred = 1;
}

message lep {
  lfq frep = 1;
}

