#
# Autogenerated by Thrift Compiler (0.20.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys

from thrift.transport import TTransport
all_structs = []


class ErrorCode(object):
    UNKNOWN = 1
    UNAUTHORIZED = 2
    INVALID_GAME_SESSION = 3
    CONNECTION_FAILED = 1001
    INVALID_CREDENTIALS = 1002
    AUTH_NOT_LOGGED_IN = 2001
    AUTH_BAN = 2002
    AUTH_BLACKLIST = 2003
    AUTH_LOCKED = 2004
    AUTH_DELETED = 2005
    AUTH_RESETANKAMA = 2006
    AUTH_OTPTIMEFAILED = 2007
    AUTH_SECURITYCARD = 2008
    AUTH_BRUTEFORCE = 2009
    AUTH_FAILED = 2010
    AUTH_PARTNER = 2011
    AUTH_MAILNOVALID = 2012
    AUTH_BETACLOSED = 2013
    AUTH_NOACCOUNT = 2014
    AUTH_ACCOUNT_LINKED = 2015
    AUTH_ACCOUNT_INVALID = 2016
    AUTH_ACCOUNT_SHIELDED = 2017
    UPDATER_CODE_RANGE = 3001
    SETTINGS_KEY_NOT_FOUND = 4001
    SETTINGS_INVALID_VALUE = 4002
    USER_INFO_UNAVAILABLE = 5001

    _VALUES_TO_NAMES = {
        1: "UNKNOWN",
        2: "UNAUTHORIZED",
        3: "INVALID_GAME_SESSION",
        1001: "CONNECTION_FAILED",
        1002: "INVALID_CREDENTIALS",
        2001: "AUTH_NOT_LOGGED_IN",
        2002: "AUTH_BAN",
        2003: "AUTH_BLACKLIST",
        2004: "AUTH_LOCKED",
        2005: "AUTH_DELETED",
        2006: "AUTH_RESETANKAMA",
        2007: "AUTH_OTPTIMEFAILED",
        2008: "AUTH_SECURITYCARD",
        2009: "AUTH_BRUTEFORCE",
        2010: "AUTH_FAILED",
        2011: "AUTH_PARTNER",
        2012: "AUTH_MAILNOVALID",
        2013: "AUTH_BETACLOSED",
        2014: "AUTH_NOACCOUNT",
        2015: "AUTH_ACCOUNT_LINKED",
        2016: "AUTH_ACCOUNT_INVALID",
        2017: "AUTH_ACCOUNT_SHIELDED",
        3001: "UPDATER_CODE_RANGE",
        4001: "SETTINGS_KEY_NOT_FOUND",
        4002: "SETTINGS_INVALID_VALUE",
        5001: "USER_INFO_UNAVAILABLE",
    }

    _NAMES_TO_VALUES = {
        "UNKNOWN": 1,
        "UNAUTHORIZED": 2,
        "INVALID_GAME_SESSION": 3,
        "CONNECTION_FAILED": 1001,
        "INVALID_CREDENTIALS": 1002,
        "AUTH_NOT_LOGGED_IN": 2001,
        "AUTH_BAN": 2002,
        "AUTH_BLACKLIST": 2003,
        "AUTH_LOCKED": 2004,
        "AUTH_DELETED": 2005,
        "AUTH_RESETANKAMA": 2006,
        "AUTH_OTPTIMEFAILED": 2007,
        "AUTH_SECURITYCARD": 2008,
        "AUTH_BRUTEFORCE": 2009,
        "AUTH_FAILED": 2010,
        "AUTH_PARTNER": 2011,
        "AUTH_MAILNOVALID": 2012,
        "AUTH_BETACLOSED": 2013,
        "AUTH_NOACCOUNT": 2014,
        "AUTH_ACCOUNT_LINKED": 2015,
        "AUTH_ACCOUNT_INVALID": 2016,
        "AUTH_ACCOUNT_SHIELDED": 2017,
        "UPDATER_CODE_RANGE": 3001,
        "SETTINGS_KEY_NOT_FOUND": 4001,
        "SETTINGS_INVALID_VALUE": 4002,
        "USER_INFO_UNAVAILABLE": 5001,
    }


class ZaapError(TException):
    """
    Attributes:
     - code
     - details

    """


    def __init__(self, code=None, details=None,):
        super(ZaapError, self).__setattr__('code', code)
        super(ZaapError, self).__setattr__('details', details)

    def __setattr__(self, *args):
        raise TypeError("can't modify immutable instance")

    def __delattr__(self, *args):
        raise TypeError("can't modify immutable instance")

    def __hash__(self):
        return hash(self.__class__) ^ hash((self.code, self.details, ))

    @classmethod
    def read(cls, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and cls.thrift_spec is not None:
            return iprot._fast_decode(None, iprot, [cls, cls.thrift_spec])
        iprot.readStructBegin()
        code = None
        details = None
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    code = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRING:
                    details = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()
        return cls(
            code=code,
            details=details,
        )

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('ZaapError')
        if self.code is not None:
            oprot.writeFieldBegin('code', TType.I32, 1)
            oprot.writeI32(self.code)
            oprot.writeFieldEnd()
        if self.details is not None:
            oprot.writeFieldBegin('details', TType.STRING, 2)
            oprot.writeString(self.details.encode('utf-8') if sys.version_info[0] == 2 else self.details)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        if self.code is None:
            raise TProtocolException(message='Required field code is unset!')
        return

    def __str__(self):
        return repr(self)

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(ZaapError)
ZaapError.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'code', None, None, ),  # 1
    (2, TType.STRING, 'details', 'UTF8', None, ),  # 2
)
fix_spec(all_structs)
del all_structs
