# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: account_status.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'account_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import game_message_pb2 as game__message__pb2
import report_pb2 as report__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61\x63\x63ount_status.proto\x12-com.ankama.dofus.server.game.protocol.account\x1a\x0c\x63ommon.proto\x1a\x12game_message.proto\x1a\x0creport.proto\"\x9b\x02\n\x16\x41\x63\x63ountRoleStatusEvent\x12l\n\x0cunknown_gfaj\x18\x01 \x01(\x0e\x32V.com.ankama.dofus.server.game.protocol.account.AccountRoleStatusEvent.UnknownGfajValue\x12\x14\n\x0cunknown_gfak\x18\x02 \x01(\x08\x12\x45\n\x04role\x18\x03 \x01(\x0e\x32\x37.com.ankama.dofus.server.game.protocol.common.Hierarchy\"6\n\x10UnknownGfajValue\x12\"\n\x1eUNKNOWN_GFAJ_VALUE_UNSPECIFIED\x10\x00\"\xf4\x01\n\x19\x41\x63\x63ountSecurityFlagsEvent\x12n\n\x0esecurity_flags\x18\x01 \x01(\x0b\x32V.com.ankama.dofus.server.game.protocol.account.AccountSecurityFlagsEvent.SecurityFlags\x1ag\n\rSecurityFlags\x12\x14\n\x0cunknown_gfap\x18\x01 \x01(\x08\x12\x14\n\x0cunknown_gfaq\x18\x02 \x01(\x08\x12\x14\n\x0cunknown_gfas\x18\x03 \x01(\x08\x12\x14\n\x0cunknown_gfat\x18\x04 \x01(\x08\"7\n\x1bSessionElapsedDurationEvent\x12\x18\n\x10\x64uration_seconds\x18\x01 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCOUNTROLESTATUSEVENT']._serialized_start=120
  _globals['_ACCOUNTROLESTATUSEVENT']._serialized_end=403
  _globals['_ACCOUNTROLESTATUSEVENT_UNKNOWNGFAJVALUE']._serialized_start=349
  _globals['_ACCOUNTROLESTATUSEVENT_UNKNOWNGFAJVALUE']._serialized_end=403
  _globals['_ACCOUNTSECURITYFLAGSEVENT']._serialized_start=406
  _globals['_ACCOUNTSECURITYFLAGSEVENT']._serialized_end=650
  _globals['_ACCOUNTSECURITYFLAGSEVENT_SECURITYFLAGS']._serialized_start=547
  _globals['_ACCOUNTSECURITYFLAGSEVENT_SECURITYFLAGS']._serialized_end=650
  _globals['_SESSIONELAPSEDDURATIONEVENT']._serialized_start=652
  _globals['_SESSIONELAPSEDDURATIONEVENT']._serialized_end=707
# @@protoc_insertion_point(module_scope)
