syntax = "proto3";

import "common.proto";

package com.ankama.dofus.server.game.protocol.guild.raid;

enum UnknownTwoHundredFiftyFive {
	UNKNOWN_TWO_HUNDRED_FIFTY_FIVE = 0;
}

enum UnknownTwoHundredFiftySix {
	UNKNOWN_TWO_HUNDRED_FIFTY_SIX = 0;
}

enum UnknownTwoHundredFiftySeven {
	UNKNOWN_TWO_HUNDRED_FIFTY_SEVEN = 0;
}

enum UnknownTwoHundredFiftyEight {
	UNKNOWN_TWO_HUNDRED_FIFTY_EIGHT = 0;
}

enum UnknownTwoHundredFiftyNine {
	UNKNOWN_TWO_HUNDRED_FIFTY_NINE = 0;
}

message UnknownTwoHundredSixty {}

enum UnknownTwoHundredSixtyOne {
	UNKNOWN_TWO_HUNDRED_SIXTY_ONE = 0;
}

enum UnknownTwoHundredSixtyTwo {
	UNKNOWN_TWO_HUNDRED_SIXTY_TWO = 0;
}

enum UnknownTwoHundredSixtyThree {
	UNKNOWN_TWO_HUNDRED_SIXTY_THREE = 0;
}

enum UnknownTwoHundredSixtyFour {
	UNKNOWN_TWO_HUNDRED_SIXTY_FOUR = 0;
}

enum UnknownTwoHundredSixtyFive {
	UNKNOWN_TWO_HUNDRED_SIXTY_FIVE = 0;
}

enum UnknownTwoHundredSixtySix {
	UNKNOWN_TWO_HUNDRED_SIXTY_SIX = 0;
}

message UnknownTwoHundredSixtySeven {}

enum UnknownTwoHundredSixtyEight {
	UNKNOWN_TWO_HUNDRED_SIXTY_EIGHT = 0;
}

message UnknownTwoHundredSixtyNine {}

message UnknownTwoHundredSeventy {}

enum UnknownTwoHundredSeventyOne {
	UNKNOWN_TWO_HUNDRED_SEVENTY_ONE = 0;
}

enum UnknownTwoHundredSeventyTwo {
	UNKNOWN_TWO_HUNDRED_SEVENTY_TWO = 0;
}


message UnknownTwoHundredSeventyThree {
	UnknownTwoHundredFiftyFive unknown_five_hundred_thirteen = 1;
}

message UnknownTwoHundredSeventyFour {
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredThirtyFive unknown_five_hundred_fourteen = 1;
	string unknown_five_hundred_fifteen = 2;
}

message UnknownThreeHundredThirtyFive {
	map<string, UnknownTwoHundredSixtySeven> unknown_six_hundred_twenty = 1;
	int32 unknown_six_hundred_twenty_one = 2;
	string unknown_six_hundred_twenty_two = 3;
	string unknown_six_hundred_twenty_three = 4;
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredTwentyEight unknown_six_hundred_twenty_four = 5;
}

message UnknownThreeHundredTwentyEight {
	int32 unknown_six_hundred_eight = 1;
	map<int32, UnknownThreeHundredTwentyNine> unknown_six_hundred_nine = 2;
	int32 unknown_six_hundred_ten = 3;
	map<int32, int32> unknown_six_hundred_eleven = 4;
	enum UnknownThreeHundredTwentyNine {
		UNKNOWN_THREE_HUNDRED_TWENTY_NINE_UNSPECIFIED = 0;
	}
}

message UnknownTwoHundredSeventySix {
	UnknownTwoHundredFiftySix unknown_five_hundred_sixteen = 1;
}

message UnknownTwoHundredSeventyEight {
	UnknownTwoHundredFiftySeven unknown_five_hundred_seventeen = 1;
}

message UnknownTwoHundredEightyOne {
	.com.ankama.dofus.server.game.protocol.guild.raid.GuildRaidLadderCategory unknown_five_hundred_twenty = 1;
	int32 unknown_five_hundred_twenty_one = 2;
	.com.ankama.dofus.server.game.protocol.guild.raid.GuildRaidLadderEntry unknown_five_hundred_twenty_two = 3;
}

message GuildRaidLadderCategory {
	int32 unknown_four_hundred_ninety_two = 1;
	repeated .com.ankama.dofus.server.game.protocol.guild.raid.GuildRaidLadderEntry unknown_four_hundred_ninety_three = 2;
}

message GuildRaidLadderEntry {
	int32 unknown_four_hundred_ninety_four = 1;
	int32 unknown_four_hundred_ninety_five = 2;
	int64 unknown_four_hundred_ninety_six = 3;
	.com.ankama.dofus.server.game.protocol.guild.raid.GuildRaidLadderGuild unknown_four_hundred_ninety_seven = 4;
}

message GuildRaidLadderGuild {
	string unknown_five_hundred_two = 1;
	.com.ankama.dofus.server.game.protocol.common.SocialEmblem unknown_five_hundred_three = 2;
	string unknown_five_hundred_four = 3;
}

message UnknownTwoHundredEightyTwo {
	UnknownTwoHundredFiftyEight unknown_five_hundred_twenty_three = 1;
}

message UnknownTwoHundredEightyThree {
	int32 unknown_five_hundred_twenty_four = 1;
	repeated .com.ankama.dofus.server.game.protocol.guild.raid.UnknownTwoHundredEightyFive unknown_five_hundred_twenty_five = 2;
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredTwo unknown_five_hundred_twenty_six = 3;
	string unknown_five_hundred_twenty_seven = 4;
}

message UnknownTwoHundredEightyFive {
	int32 unknown_five_hundred_thirty_one = 1;
	bool unknown_five_hundred_thirty_two = 2;
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownTwoHundredEightySeven unknown_five_hundred_thirty_four = 4;
	bool unknown_five_hundred_thirty_three = 5;
}

message UnknownTwoHundredEightySeven {
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownTwoHundredEightySeven.UnknownTwoHundredEightyEight unknown_five_hundred_thirty_six = 2;
	message UnknownTwoHundredEightyEight {
	}
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredFour unknown_five_hundred_thirty_five = 3;
}

message UnknownThreeHundredFour {
	int32 unknown_five_hundred_fifty_seven = 1;
	UnknownThreeHundredFive unknown_five_hundred_fifty_eight = 2;
	int64 unknown_five_hundred_fifty_nine = 3;
	int32 unknown_five_hundred_sixty = 4;
	string unknown_five_hundred_sixty_one = 5;
	.com.ankama.dofus.server.game.protocol.common.CharacterStatus unknown_five_hundred_sixty_two = 6;
	string unknown_five_hundred_sixty_three = 7;
	enum UnknownThreeHundredFive {
		UNKNOWN_THREE_HUNDRED_FIVE_UNSPECIFIED = 0;
		UNKNOWN_THREE_HUNDRED_FIVE_1 = 1;
	}
}

message UnknownThreeHundredTwo {
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredTwo.UnknownThreeHundredThree unknown_five_hundred_fifty_four = 1;
	string unknown_five_hundred_fifty_five = 2;
	string unknown_five_hundred_fifty_six = 3;
	message UnknownThreeHundredThree {
	}
}

message UnknownTwoHundredEightyFour {
	string unknown_five_hundred_twenty_eight = 1;
	string unknown_five_hundred_twenty_nine = 2;
	UnknownTwoHundredFiftyNine unknown_five_hundred_thirty = 3;
}

message GuildRaidLadderEvent {
	map<int32, .com.ankama.dofus.server.game.protocol.guild.raid.GuildRaidLadderCategory> unknown_four_hundred_ninety_eight = 1;
	map<int32, .com.ankama.dofus.server.game.protocol.guild.raid.GuildRaidLadderCategory> unknown_four_hundred_ninety_nine = 2;
	map<int32, .com.ankama.dofus.server.game.protocol.guild.raid.GuildRaidLadderEntry> unknown_five_hundred = 3;
	map<int32, .com.ankama.dofus.server.game.protocol.guild.raid.GuildRaidLadderEntry> unknown_five_hundred_one = 4;
}

message GuildRaidRewardsInformationEvent {
	map<string, UnknownTwoHundredFiftyTwo> unknown_five_hundred_nine = 1;
	map<int32, .com.ankama.dofus.server.game.protocol.guild.raid.GuildRaidRewardsInformationEvent.UnknownTwoHundredFiftyThree> unknown_five_hundred_ten = 2;
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredFortySix unknown_five_hundred_eleven = 3;
	.com.ankama.dofus.server.game.protocol.guild.raid.GuildRaidRewardsInformationEvent.UnknownTwoHundredFiftyFour unknown_five_hundred_twelve = 4;
	message UnknownTwoHundredFiftyThree {
		repeated int32 unknown_five_hundred_seven = 1;
		int32 unknown_five_hundred_eight = 2;
	}
	message UnknownTwoHundredFiftyFour {
}
	message UnknownTwoHundredFiftyTwo {
	}
}

message UnknownThreeHundredFortySix {
	.com.ankama.dofus.server.game.protocol.guild.raid.GuildRaidLadderGuild unknown_six_hundred_thirty_six = 1;
	string unknown_six_hundred_thirty_seven = 2;
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownTwoHundredEightyThree unknown_six_hundred_thirty_eight = 3;
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredThirtyFour unknown_six_hundred_thirty_nine = 4;
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredNine unknown_six_hundred_forty = 5;
}

message UnknownThreeHundredThirtyFour {
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredTwo unknown_six_hundred_sixteen = 1;
	repeated .com.ankama.dofus.server.game.protocol.guild.raid.UnknownTwoHundredEightyFive unknown_six_hundred_seventeen = 2;
	int32 unknown_six_hundred_eighteen = 3;
	repeated .com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredFour unknown_six_hundred_nineteen = 4;
}

message UnknownThreeHundredNine {
	repeated string unknown_five_hundred_sixty_six = 1;
	string unknown_five_hundred_sixty_seven = 2;
	repeated .com.ankama.dofus.server.game.protocol.guild.raid.UnknownTwoHundredEightyFive unknown_five_hundred_sixty_eight = 3;
	int32 unknown_five_hundred_sixty_nine = 4;
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredTwo unknown_five_hundred_seventy = 5;
}

message UnknownTwoHundredEightyNine {
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownTwoHundredEightyNine.UnknownTwoHundredNinetyOne unknown_five_hundred_thirty_seven = 1;
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownTwoHundredEightyNine.UnknownTwoHundredNinety unknown_five_hundred_thirty_eight = 3;
	UnknownTwoHundredSixtyOne unknown_five_hundred_thirty_nine = 4;
	message UnknownTwoHundredNinety {
	}
	message UnknownTwoHundredNinetyOne {
	}
}

message UnknownTwoHundredNinetyTwo {
	string unknown_five_hundred_forty = 1;
	string unknown_five_hundred_forty_one = 2;
}

message UnknownTwoHundredNinetyThree {
	UnknownTwoHundredSixtyTwo unknown_five_hundred_forty_two = 1;
}

message UnknownTwoHundredNinetyFour {
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredThirtyFour unknown_five_hundred_forty_three = 1;
	string unknown_five_hundred_forty_four = 2;
}

message UnknownTwoHundredNinetyFive {
	string unknown_five_hundred_forty_five = 1;
	string unknown_five_hundred_forty_six = 2;
	bool unknown_five_hundred_forty_seven = 3;
}

message UnknownTwoHundredNinetySeven {
	int32 unknown_five_hundred_forty_nine = 2;
	repeated int32 unknown_five_hundred_fifty = 3;
	bool unknown_five_hundred_fifty_one = 4;
	map<int32, UnknownTwoHundredNinetyEight> unknown_five_hundred_fifty_two = 5;
	int64 unknown_five_hundred_forty_eight = 6;
	enum UnknownTwoHundredNinetyEight {
		UNKNOWN_TWO_HUNDRED_NINETY_EIGHT_UNSPECIFIED = 0;
	}
}

message UnknownTwoHundredNinetyNine {
	UnknownThreeHundred unknown_five_hundred_fifty_three = 1;
	enum UnknownThreeHundred {
		UNKNOWN_THREE_HUNDRED_UNSPECIFIED = 0;
	}
}

message UnknownThreeHundredSix {
	int32 unknown_five_hundred_sixty_four = 1;
}

message UnknownThreeHundredSeven {
	UnknownThreeHundredEight unknown_five_hundred_sixty_five = 1;
	enum UnknownThreeHundredEight {
		UNKNOWN_THREE_HUNDRED_EIGHT_UNSPECIFIED = 0;
	}
}

message UnknownThreeHundredTen {
	UnknownTwoHundredSixtyThree unknown_five_hundred_seventy_one = 1;
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredFortySix unknown_five_hundred_seventy_two = 2;
}

message UnknownThreeHundredEleven {
	bool unknown_five_hundred_seventy_three = 1;
}

message UnknownThreeHundredTwelve {
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredTwentyEight unknown_five_hundred_seventy_four = 1;
	string unknown_five_hundred_seventy_five = 2;
}

message UnknownThreeHundredThirteen {
	string unknown_five_hundred_seventy_six = 1;
	string unknown_five_hundred_seventy_seven = 2;
}

message UnknownThreeHundredFourteen {
	int32 unknown_five_hundred_seventy_eight = 1;
	string unknown_five_hundred_seventy_nine = 2;
}

message UnknownThreeHundredFifteen {
	int32 unknown_five_hundred_eighty = 1;
}

message UnknownThreeHundredSixteen {
	string unknown_five_hundred_eighty_one = 1;
	string unknown_five_hundred_eighty_two = 2;
}

message UnknownThreeHundredSeventeen {
	UnknownTwoHundredSixtyFour unknown_five_hundred_eighty_three = 1;
}

message UnknownThreeHundredEighteen {
	map<int32, .com.ankama.dofus.server.game.protocol.guild.raid.GuildRaidLadderEntry> unknown_five_hundred_eighty_four = 1;
	map<int32, .com.ankama.dofus.server.game.protocol.guild.raid.GuildRaidLadderCategory> unknown_five_hundred_eighty_five = 2;
}

message UnknownThreeHundredNineteen {
	UnknownTwoHundredSixtyFive unknown_five_hundred_eighty_six = 1;
}

message UnknownThreeHundredTwentyTwo {
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredFortySix unknown_five_hundred_ninety_three = 1;
}

message UnknownThreeHundredTwentyFour {
	bool unknown_five_hundred_ninety_four = 1;
}

message UnknownThreeHundredTwentyFive {
	string unknown_five_hundred_ninety_five = 1;
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownTwoHundredEightyThree unknown_five_hundred_ninety_six = 2;
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredNine unknown_five_hundred_ninety_seven = 3;
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredTwentySeven unknown_five_hundred_ninety_eight = 4;
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredThirtyFour unknown_five_hundred_ninety_nine = 5;
}

message UnknownThreeHundredTwentySeven {
	string unknown_six_hundred_one = 1;
	repeated .com.ankama.dofus.server.game.protocol.guild.raid.UnknownTwoHundredEightyFive unknown_six_hundred_two = 2;
	int32 unknown_six_hundred_three = 3;
	int64 unknown_six_hundred_four = 4;
	repeated int32 unknown_six_hundred_five = 5;
	int32 unknown_six_hundred_six = 6;
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredTwo unknown_six_hundred_seven = 7;
}

message UnknownThreeHundredTwentySix {
	string unknown_six_hundred = 1;
}

message UnknownThreeHundredThirty {
	string unknown_six_hundred_twelve = 1;
	string unknown_six_hundred_thirteen = 2;
	.com.ankama.dofus.server.game.protocol.common.CharacterStatus unknown_six_hundred_fourteen = 3;
}

message UnknownThreeHundredThirtyTwo {
	UnknownTwoHundredSixtySix unknown_six_hundred_fifteen = 1;
}

message UnknownThreeHundredThirtySix {
	string unknown_six_hundred_twenty_five = 1;
	map<string, int32> unknown_six_hundred_twenty_six = 2;
}

message UnknownThreeHundredThirtySeven {
	repeated bool unknown_six_hundred_twenty_seven = 1;
}

message UnknownThreeHundredThirtyEight {
	.com.ankama.dofus.server.game.protocol.guild.raid.GuildRaidLadderGuild unknown_six_hundred_twenty_eight = 1;
	int32 unknown_six_hundred_twenty_nine = 2;
}

message UnknownThreeHundredForty {
	repeated .com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredFifteen unknown_six_hundred_thirty = 1;
}

message UnknownThreeHundredFortyOne {
	string unknown_six_hundred_thirty_one = 1;
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredThirtyFive unknown_six_hundred_thirty_two = 2;
}

message UnknownThreeHundredFortyTwo {
	int32 unknown_six_hundred_thirty_three = 1;
}

message GuildRaidOverviewEvent {
	.com.ankama.dofus.server.game.protocol.guild.raid.GuildRaidOverviewEvent.UnknownTwoHundredFiftyOne unknown_five_hundred_five = 1;
	message UnknownTwoHundredFiftyOne {
	}
	enum UnknownTwoHundredFifty {
		UNKNOWN_TWO_HUNDRED_FIFTY_UNSPECIFIED = 0;
		UNKNOWN_TWO_HUNDRED_FIFTY_1 = 1;
	}
}

message UnknownThreeHundredFortyFour {
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredFortyFour.UnknownThreeHundredFortyFive unknown_six_hundred_thirty_four = 1;
	UnknownTwoHundredSixtyEight unknown_six_hundred_thirty_five = 2;
	message UnknownThreeHundredFortyFive {
	}
}

message UnknownThreeHundredFortyNine {
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredFortyNine.UnknownThreeHundredFiftyTwo unknown_six_hundred_forty_one = 2;
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredFortyNine.UnknownThreeHundredFifty unknown_six_hundred_forty_two = 3;
	.com.ankama.dofus.server.game.protocol.guild.raid.UnknownThreeHundredFortyNine.UnknownThreeHundredFiftyOne unknown_six_hundred_forty_three = 4;
	message UnknownThreeHundredFifty {
	}
	message UnknownThreeHundredFiftyOne {
	}
	message UnknownThreeHundredFiftyTwo {
	}
}

message UnknownThreeHundredFiftyThree {
	string unknown_six_hundred_forty_four = 1;
	string unknown_six_hundred_forty_five = 2;
}

message UnknownThreeHundredFiftyFour {
	UnknownTwoHundredSeventyOne unknown_six_hundred_forty_six = 1;
}

message UnknownThreeHundredFiftyFive {
	int32 unknown_six_hundred_forty_seven = 1;
	string unknown_six_hundred_forty_eight = 2;
}

message UnknownThreeHundredFiftySix {
	UnknownTwoHundredSeventyTwo unknown_six_hundred_forty_nine = 1;
}

message UnknownThreeHundredFiftyEight {
	int32 unknown_six_hundred_fifty = 1;
	int32 unknown_six_hundred_fifty_one = 2;
}

message GuildRaidLadderRequest {
}

message GuildRaidRewardsInformationRequest {
}

message GuildRaidOverviewRequest {
}

message GuildRaidPurchaseInformationRequest {
}

message GuildRaidPurchaseInformationEvent {
	oneof result {
		GuildRaidPurchaseInformationFailure failure = 1;
		GuildRaidPurchaseInformationOptions options = 2;
	}
	message GuildRaidPurchaseInformationFailure {
	}
	message GuildRaidPurchaseInformationOptions {
		int32 unknown_five_hundred_six = 1;
	}
}

message UnknownTwoHundredSeventySeven {
}

message UnknownTwoHundredSeventyFive {
}

message UnknownTwoHundredSeventyNine {
}

message UnknownTwoHundredEighty {
	int64 unknown_five_hundred_eighteen = 1;
	string unknown_five_hundred_nineteen = 2;
}

message UnknownTwoHundredEightySix {
}

message UnknownTwoHundredNinetySix {
}

message UnknownThreeHundredOne {
}

message UnknownThreeHundredTwenty {
	bool unknown_five_hundred_eighty_seven = 1;
	string unknown_five_hundred_eighty_eight = 3;
	UnknownThreeHundredTwentyOne unknown_five_hundred_eighty_nine = 4;
	bool unknown_five_hundred_ninety = 5;
	int32 unknown_five_hundred_ninety_one = 6;
	int32 unknown_five_hundred_ninety_two = 7;
	enum UnknownThreeHundredTwentyOne {
		UNKNOWN_THREE_HUNDRED_TWENTY_ONE_UNSPECIFIED = 0;
		UNKNOWN_THREE_HUNDRED_TWENTY_ONE_1 = 1;
	}
}

message UnknownThreeHundredTwentyThree {
}

message UnknownThreeHundredThirtyOne {
}

message UnknownThreeHundredThirtyThree {
}

message UnknownThreeHundredThirtyNine {
}

message UnknownThreeHundredFortyThree {
}

message UnknownThreeHundredFortySeven {
}

message UnknownThreeHundredFortyEight {
}

message UnknownThreeHundredFiftySeven {
}
