# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: guild_mission_reward.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'guild_mission_reward.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aguild_mission_reward.proto\x12:com.ankama.dofus.server.game.protocol.guild.mission.reward\x1a\x0c\x63ommon.proto\"\xb2\x02\n\x18GuildMissionRewardsEvent\x12|\n\x07rewards\x18\x01 \x01(\x0b\x32k.com.ankama.dofus.server.game.protocol.guild.mission.reward.GuildMissionRewardsEvent.GuildMissionRewardList\x1a\x97\x01\n\x16GuildMissionRewardList\x12\'\n\x1funknown_four_hundred_ninety_one\x18\x01 \x01(\x05\x12T\n\x07rewards\x18\x02 \x03(\x0b\x32\x43.com.ankama.dofus.server.game.protocol.common.ObjectGidWithQuantity\"\x1c\n\x1aGuildMissionRewardsRequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'guild_mission_reward_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GUILDMISSIONREWARDSEVENT']._serialized_start=105
  _globals['_GUILDMISSIONREWARDSEVENT']._serialized_end=411
  _globals['_GUILDMISSIONREWARDSEVENT_GUILDMISSIONREWARDLIST']._serialized_start=260
  _globals['_GUILDMISSIONREWARDSEVENT_GUILDMISSIONREWARDLIST']._serialized_end=411
  _globals['_GUILDMISSIONREWARDSREQUEST']._serialized_start=413
  _globals['_GUILDMISSIONREWARDSREQUEST']._serialized_end=441
# @@protoc_insertion_point(module_scope)
