# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: guild_mission_listener.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'guild_mission_listener.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cguild_mission_listener.proto\x12<com.ankama.dofus.server.game.protocol.guild.mission.listener\" \n\x1eGuildMissionStartListenerEvent\"\xfe\x02\n GuildMissionStartListenerRequest\x12\x94\x01\n\x10listener_options\x18\x01 \x01(\x0b\x32z.com.ankama.dofus.server.game.protocol.guild.mission.listener.GuildMissionStartListenerRequest.GuildMissionListenerOptions\x1a\xc2\x01\n\x1bGuildMissionListenerOptions\x12)\n!unknown_four_hundred_eighty_seven\x18\x01 \x01(\x05\x12)\n!unknown_four_hundred_eighty_eight\x18\x02 \x01(\x03\x12(\n unknown_four_hundred_eighty_nine\x18\x03 \x03(\x03\x12#\n\x1bunknown_four_hundred_ninety\x18\x04 \x01(\x08\"\x1f\n\x1dGuildMissionStopListenerEvent\"!\n\x1fGuildMissionStopListenerRequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'guild_mission_listener_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GUILDMISSIONSTARTLISTENEREVENT']._serialized_start=94
  _globals['_GUILDMISSIONSTARTLISTENEREVENT']._serialized_end=126
  _globals['_GUILDMISSIONSTARTLISTENERREQUEST']._serialized_start=129
  _globals['_GUILDMISSIONSTARTLISTENERREQUEST']._serialized_end=511
  _globals['_GUILDMISSIONSTARTLISTENERREQUEST_GUILDMISSIONLISTENEROPTIONS']._serialized_start=317
  _globals['_GUILDMISSIONSTARTLISTENERREQUEST_GUILDMISSIONLISTENEROPTIONS']._serialized_end=511
  _globals['_GUILDMISSIONSTOPLISTENEREVENT']._serialized_start=513
  _globals['_GUILDMISSIONSTOPLISTENEREVENT']._serialized_end=544
  _globals['_GUILDMISSIONSTOPLISTENERREQUEST']._serialized_start=546
  _globals['_GUILDMISSIONSTOPLISTENERREQUEST']._serialized_end=579
# @@protoc_insertion_point(module_scope)
