# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: guild_chest.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'guild_chest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11guild_chest.proto\x12\x31\x63om.ankama.dofus.server.game.protocol.guild.chest\"5\n\"GuildChestCurrentListenersAddEvent\x12\x0f\n\x07players\x18\x01 \x01(\t\"2\n\x1fGuildChestCurrentListenersEvent\x12\x0f\n\x07players\x18\x01 \x03(\t\"8\n%GuildChestCurrentListenersRemoveEvent\x12\x0f\n\x07players\x18\x01 \x01(\t\")\n\'GuildChestStructureStopListeningRequest\"\xeb\x01\n\x1fGuildChestTabContributionsEvent\x12v\n\rcontributions\x18\x01 \x03(\x0b\x32_.com.ankama.dofus.server.game.protocol.guild.chest.GuildChestTabContributionsEvent.Contribution\x1aP\n\x0c\x43ontribution\x12\x16\n\x0e\x63ontributor_id\x18\x01 \x01(\x03\x12\x18\n\x10\x63ontributor_name\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03\"0\n\x1aGuildChestTabSelectRequest\x12\x12\n\ntab_number\x18\x01 \x01(\x05\"k\n\x1aGuildChestTabUpdateRequest\x12\x12\n\ntab_number\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05picto\x18\x03 \x01(\x05\x12\x1c\n\x14\x64rop_type_limitation\x18\x04 \x03(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'guild_chest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GUILDCHESTCURRENTLISTENERSADDEVENT']._serialized_start=72
  _globals['_GUILDCHESTCURRENTLISTENERSADDEVENT']._serialized_end=125
  _globals['_GUILDCHESTCURRENTLISTENERSEVENT']._serialized_start=127
  _globals['_GUILDCHESTCURRENTLISTENERSEVENT']._serialized_end=177
  _globals['_GUILDCHESTCURRENTLISTENERSREMOVEEVENT']._serialized_start=179
  _globals['_GUILDCHESTCURRENTLISTENERSREMOVEEVENT']._serialized_end=235
  _globals['_GUILDCHESTSTRUCTURESTOPLISTENINGREQUEST']._serialized_start=237
  _globals['_GUILDCHESTSTRUCTURESTOPLISTENINGREQUEST']._serialized_end=278
  _globals['_GUILDCHESTTABCONTRIBUTIONSEVENT']._serialized_start=281
  _globals['_GUILDCHESTTABCONTRIBUTIONSEVENT']._serialized_end=516
  _globals['_GUILDCHESTTABCONTRIBUTIONSEVENT_CONTRIBUTION']._serialized_start=436
  _globals['_GUILDCHESTTABCONTRIBUTIONSEVENT_CONTRIBUTION']._serialized_end=516
  _globals['_GUILDCHESTTABSELECTREQUEST']._serialized_start=518
  _globals['_GUILDCHESTTABSELECTREQUEST']._serialized_end=566
  _globals['_GUILDCHESTTABUPDATEREQUEST']._serialized_start=568
  _globals['_GUILDCHESTTABUPDATEREQUEST']._serialized_end=675
# @@protoc_insertion_point(module_scope)
