syntax = "proto3";

import "common.proto";
import "game_message.proto";
import "report.proto";
import "ladder.proto";

package com.ankama.dofus.server.game.protocol.ladder.infinite_dream;

message InfiniteDreamLadderPageEvent {
	repeated .com.ankama.dofus.server.game.protocol.ladder.infinite_dream.InfiniteDreamLadderEntry entries = 1;
}

message UnknownIqk {
	int32 unknown_fqrv = 1;
	string unknown_fqrw = 2;
}

message InfiniteDreamLadderSelfRankRequest {
	int32 server_id = 1;
}

message UnknownIqm {
	repeated .com.ankama.dofus.server.game.protocol.ladder.infinite_dream.InfiniteDreamLadderEntry entries = 1;
}

message InfiniteDreamLadderPageRequest {
	int32 server_id = 1;
}

message InfiniteDreamLadderSelfRankEvent {
	.com.ankama.dofus.server.game.protocol.ladder.infinite_dream.InfiniteDreamLadderEntry entry = 1;
}

message InfiniteDreamLadderEntry {
	int32 unknown_fqsj = 1;
	int64 rank = 2;
	.com.ankama.dofus.server.game.protocol.ladder.LadderCharacter player = 3;
	int32 breed_id = 4;
	string done_date = 5;
	int32 wave = 6;
}
