# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ladder_experience.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'ladder_experience.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ladder_pb2 as ladder__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17ladder_experience.proto\x12\x37\x63om.ankama.dofus.server.game.protocol.ladder.experience\x1a\x0cladder.proto\"Y\n\x1b\x45xperienceLadderPageRequest\x12\'\n\x1funknown_six_hundred_seventy_six\x18\x01 \x03(\x08\x12\x11\n\tserver_id\x18\x02 \x01(\x05\"4\n\x1f\x45xperienceLadderSelfRankRequest\x12\x11\n\tserver_id\x18\x01 \x01(\x05\"\x8b\x01\n\x15\x45xperienceLadderEntry\x12\x12\n\nexperience\x18\x01 \x01(\x03\x12P\n\tcharacter\x18\x02 \x01(\x0b\x32=.com.ankama.dofus.server.game.protocol.ladder.LadderCharacter\x12\x0c\n\x04rank\x18\x03 \x01(\x03\"|\n\x19\x45xperienceLadderPageEvent\x12_\n\x07\x65ntries\x18\x01 \x03(\x0b\x32N.com.ankama.dofus.server.game.protocol.ladder.experience.ExperienceLadderEntry\"u\n\x1dUnknownThreeHundredSixtySeven\x12)\n!unknown_six_hundred_seventy_seven\x18\x01 \x01(\t\x12)\n!unknown_six_hundred_seventy_eight\x18\x02 \x01(\x05\"\x80\x01\n\x1dUnknownThreeHundredSixtyEight\x12_\n\x07\x65ntries\x18\x01 \x03(\x0b\x32N.com.ankama.dofus.server.game.protocol.ladder.experience.ExperienceLadderEntry\"~\n\x1d\x45xperienceLadderSelfRankEvent\x12]\n\x05\x65ntry\x18\x01 \x01(\x0b\x32N.com.ankama.dofus.server.game.protocol.ladder.experience.ExperienceLadderEntryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ladder_experience_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXPERIENCELADDERPAGEREQUEST']._serialized_start=98
  _globals['_EXPERIENCELADDERPAGEREQUEST']._serialized_end=187
  _globals['_EXPERIENCELADDERSELFRANKREQUEST']._serialized_start=189
  _globals['_EXPERIENCELADDERSELFRANKREQUEST']._serialized_end=241
  _globals['_EXPERIENCELADDERENTRY']._serialized_start=244
  _globals['_EXPERIENCELADDERENTRY']._serialized_end=383
  _globals['_EXPERIENCELADDERPAGEEVENT']._serialized_start=385
  _globals['_EXPERIENCELADDERPAGEEVENT']._serialized_end=509
  _globals['_UNKNOWNTHREEHUNDREDSIXTYSEVEN']._serialized_start=511
  _globals['_UNKNOWNTHREEHUNDREDSIXTYSEVEN']._serialized_end=628
  _globals['_UNKNOWNTHREEHUNDREDSIXTYEIGHT']._serialized_start=631
  _globals['_UNKNOWNTHREEHUNDREDSIXTYEIGHT']._serialized_end=759
  _globals['_EXPERIENCELADDERSELFRANKEVENT']._serialized_start=761
  _globals['_EXPERIENCELADDERSELFRANKEVENT']._serialized_end=887
# @@protoc_insertion_point(module_scope)
