syntax = "proto3";

import "game_message.proto";
import "report.proto";
import "ladder.proto";

package com.ankama.dofus.server.game.protocol.ladder.experience;

message ExperienceLadderPageRequest {
	repeated bool unknown_fqqg = 1;
	int32 server_id = 2;
}

message ExperienceLadderSelfRankRequest {
	int32 server_id = 1;
}

message ExperienceLadderEntry {
	int64 experience = 1;
	.com.ankama.dofus.server.game.protocol.ladder.LadderCharacter character = 2;
	int64 rank = 3;
}

message ExperienceLadderPageEvent {
	repeated .com.ankama.dofus.server.game.protocol.ladder.experience.ExperienceLadderEntry entries = 1;
}

message UnknownIqd {
	string unknown_fqrc = 1;
	int32 unknown_fqrd = 2;
}

message UnknownIqg {
	repeated .com.ankama.dofus.server.game.protocol.ladder.experience.ExperienceLadderEntry entries = 1;
}

message ExperienceLadderSelfRankEvent {
	.com.ankama.dofus.server.game.protocol.ladder.experience.ExperienceLadderEntry entry = 1;
}

message GuildTokenConfiguration {
	.com.ankama.dofus.server.game.protocol.ladder.experience.GuildTokenConfiguration.GuildTokenItems guild_token_items = 1;
	int64 refresh_interval_milliseconds = 2;
	.com.ankama.dofus.server.game.protocol.ladder.experience.GuildTokenConfiguration.GuildTokenThresholds thresholds = 3;
	message GuildTokenThresholds {
		int64 unknown_fytt = 1;
		int32 unknown_fytu = 2;
		int32 unknown_fytv = 3;
		int32 unknown_fytw = 4;
	}
	message GuildTokenItems {
		int32 guildaton_item_id = 1;
		int32 unknown_fyul = 2;
		int32 unknown_fyum = 3;
		int32 unknown_fyun = 4;
		int32 guild_token_item_id = 5;
		int32 unknown_fyup = 6;
	}
}

message GuildTokenConfigurationEvent {
	.com.ankama.dofus.server.game.protocol.ladder.experience.GuildTokenConfiguration configuration = 1;
}
