# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ladder_infinite_dream.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'ladder_infinite_dream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import game_message_pb2 as game__message__pb2
import report_pb2 as report__pb2
import ladder_pb2 as ladder__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bladder_infinite_dream.proto\x12;com.ankama.dofus.server.game.protocol.ladder.infinite_dream\x1a\x0c\x63ommon.proto\x1a\x12game_message.proto\x1a\x0creport.proto\x1a\x0cladder.proto\"\x86\x01\n\x1cInfiniteDreamLadderPageEvent\x12\x66\n\x07\x65ntries\x18\x01 \x03(\x0b\x32U.com.ankama.dofus.server.game.protocol.ladder.infinite_dream.InfiniteDreamLadderEntry\"8\n\nUnknownIqk\x12\x14\n\x0cunknown_fqrv\x18\x01 \x01(\x05\x12\x14\n\x0cunknown_fqrw\x18\x02 \x01(\t\"7\n\"InfiniteDreamLadderSelfRankRequest\x12\x11\n\tserver_id\x18\x01 \x01(\x05\"t\n\nUnknownIqm\x12\x66\n\x07\x65ntries\x18\x01 \x03(\x0b\x32U.com.ankama.dofus.server.game.protocol.ladder.infinite_dream.InfiniteDreamLadderEntry\"3\n\x1eInfiniteDreamLadderPageRequest\x12\x11\n\tserver_id\x18\x01 \x01(\x05\"\x88\x01\n InfiniteDreamLadderSelfRankEvent\x12\x64\n\x05\x65ntry\x18\x01 \x01(\x0b\x32U.com.ankama.dofus.server.game.protocol.ladder.infinite_dream.InfiniteDreamLadderEntry\"\xc0\x01\n\x18InfiniteDreamLadderEntry\x12\x14\n\x0cunknown_fqsj\x18\x01 \x01(\x05\x12\x0c\n\x04rank\x18\x02 \x01(\x03\x12M\n\x06player\x18\x03 \x01(\x0b\x32=.com.ankama.dofus.server.game.protocol.ladder.LadderCharacter\x12\x10\n\x08\x62reed_id\x18\x04 \x01(\x05\x12\x11\n\tdone_date\x18\x05 \x01(\t\x12\x0c\n\x04wave\x18\x06 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ladder_infinite_dream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFINITEDREAMLADDERPAGEEVENT']._serialized_start=155
  _globals['_INFINITEDREAMLADDERPAGEEVENT']._serialized_end=289
  _globals['_UNKNOWNIQK']._serialized_start=291
  _globals['_UNKNOWNIQK']._serialized_end=347
  _globals['_INFINITEDREAMLADDERSELFRANKREQUEST']._serialized_start=349
  _globals['_INFINITEDREAMLADDERSELFRANKREQUEST']._serialized_end=404
  _globals['_UNKNOWNIQM']._serialized_start=406
  _globals['_UNKNOWNIQM']._serialized_end=522
  _globals['_INFINITEDREAMLADDERPAGEREQUEST']._serialized_start=524
  _globals['_INFINITEDREAMLADDERPAGEREQUEST']._serialized_end=575
  _globals['_INFINITEDREAMLADDERSELFRANKEVENT']._serialized_start=578
  _globals['_INFINITEDREAMLADDERSELFRANKEVENT']._serialized_end=714
  _globals['_INFINITEDREAMLADDERENTRY']._serialized_start=717
  _globals['_INFINITEDREAMLADDERENTRY']._serialized_end=909
# @@protoc_insertion_point(module_scope)
