syntax = "proto3";

import "arena.proto";
import "ladder.proto";

package com.ankama.dofus.server.game.protocol.ladder.arena;

enum UnknownThreeHundredSixtyTwo {
	UNKNOWN_THREE_HUNDRED_SIXTY_TWO = 0;
}


message ArenaLadderPageEvent {
	repeated .com.ankama.dofus.server.game.protocol.ladder.arena.ArenaLadderEntry ranks = 1;
}

message ArenaLadderEntry {
	int64 rank = 1;
	int32 winrate = 2;
	.com.ankama.dofus.server.game.protocol.ladder.LadderCharacter player = 3;
	int32 unknown_six_hundred_sixty_six = 4;
	int32 rating = 5;
}

message ArenaLadderSelfRankRequest {
	int32 breed_id = 1;
	.com.ankama.dofus.server.game.protocol.arena.ArenaType mode = 2;
	int32 unknown_six_hundred_sixty_eight = 3;
}

message UnknownThreeHundredSixtyThree {
	repeated .com.ankama.dofus.server.game.protocol.ladder.arena.ArenaLadderEntry entries = 1;
}

message ArenaLadderPageRequest {
	repeated bool unknown_six_hundred_sixty_seven = 1;
	.com.ankama.dofus.server.game.protocol.arena.ArenaType mode = 2;
	int32 level_range = 3;
	int32 breed_id = 4;
}

message UnknownThreeHundredSixtyFour {
	int32 unknown_six_hundred_sixty_nine = 1;
	UnknownThreeHundredSixtyTwo unknown_six_hundred_seventy = 2;
	int32 unknown_six_hundred_seventy_one = 3;
	string unknown_six_hundred_seventy_two = 4;
}

message ArenaLadderSelfRankEvent {
	.com.ankama.dofus.server.game.protocol.ladder.arena.ArenaLadderEntry entry = 1;
}
