syntax = "proto3";


package com.ankama.dofus.server.game.protocol.lobby;

enum UnknownThreeHundredSeventySeven {
	UNKNOWN_THREE_HUNDRED_SEVENTY_SEVEN = 0;
}

message UnknownThreeHundredSeventyOne {}

enum UnknownThreeHundredSeventyTwo {
	UNKNOWN_THREE_HUNDRED_SEVENTY_TWO = 0;
}

enum UnknownThreeHundredSeventyThree {
	UNKNOWN_THREE_HUNDRED_SEVENTY_THREE = 0;
}

enum UnknownThreeHundredSeventyFour {
	UNKNOWN_THREE_HUNDRED_SEVENTY_FOUR = 0;
}

enum UnknownThreeHundredSeventyFive {
	UNKNOWN_THREE_HUNDRED_SEVENTY_FIVE = 0;
}

enum UnknownThreeHundredSeventySix {
	UNKNOWN_THREE_HUNDRED_SEVENTY_SIX = 0;
}

enum UnknownThreeHundredSeventyEight {
	UNKNOWN_THREE_HUNDRED_SEVENTY_EIGHT = 0;
}

enum UnknownThreeHundredSeventyNine {
	UNKNOWN_THREE_HUNDRED_SEVENTY_NINE = 0;
}

enum UnknownThreeHundredEighty {
	UNKNOWN_THREE_HUNDRED_EIGHTY = 0;
}

enum UnknownThreeHundredEightyOne {
	UNKNOWN_THREE_HUNDRED_EIGHTY_ONE = 0;
}

enum UnknownThreeHundredEightyTwo {
	UNKNOWN_THREE_HUNDRED_EIGHTY_TWO = 0;
}


message UnknownThreeHundredEightyThree {
	string unknown_six_hundred_ninety_four = 1;
	bool unknown_six_hundred_ninety_five = 2;
}

message UnknownThreeHundredEightyFour {
	.com.ankama.dofus.server.game.protocol.lobby.UnknownThreeHundredEightyFour.UnknownThreeHundredEightyFive unknown_six_hundred_ninety_six = 1;
	message UnknownThreeHundredEightyFive {
	}
}

message UnknownThreeHundredEightySix {
	UnknownThreeHundredSeventyTwo unknown_six_hundred_ninety_seven = 1;
	string unknown_six_hundred_ninety_eight = 2;
}

message UnknownThreeHundredEightySeven {
	.com.ankama.dofus.server.game.protocol.lobby.UnknownFourHundredThirteen unknown_six_hundred_ninety_nine = 1;
}

message UnknownFourHundredThirteen {
	repeated .com.ankama.dofus.server.game.protocol.lobby.UnknownThreeHundredNinetyFive unknown_seven_hundred_forty_nine = 1;
	.com.ankama.dofus.server.game.protocol.lobby.UnknownFourHundredFour unknown_seven_hundred_fifty = 2;
	repeated .com.ankama.dofus.server.game.protocol.lobby.UnknownThreeHundredNinetyFive unknown_seven_hundred_fifty_one = 3;
}

message UnknownThreeHundredNinetyFive {
	int64 unknown_seven_hundred_ten = 1;
	string unknown_seven_hundred_eleven = 2;
	int32 unknown_seven_hundred_twelve = 3;
	int32 unknown_seven_hundred_thirteen = 4;
	string unknown_seven_hundred_fourteen = 5;
	UnknownThreeHundredSeventySix unknown_seven_hundred_fifteen = 6;
	string unknown_seven_hundred_sixteen = 7;
}

message UnknownFourHundredFour {
	int32 unknown_seven_hundred_twenty_seven = 1;
	int32 unknown_seven_hundred_twenty_eight = 2;
	int32 unknown_seven_hundred_twenty_nine = 3;
	bool unknown_seven_hundred_thirty = 4;
	string unknown_seven_hundred_thirty_one = 5;
	repeated int32 unknown_seven_hundred_thirty_two = 6;
	repeated int32 unknown_seven_hundred_thirty_three = 7;
	string unknown_seven_hundred_thirty_four = 8;
	int32 unknown_seven_hundred_thirty_five = 9;
	.com.ankama.dofus.server.game.protocol.lobby.UnknownThreeHundredNinetyFive unknown_seven_hundred_thirty_six = 10;
	repeated .com.ankama.dofus.server.game.protocol.lobby.UnknownThreeHundredNinetyFive unknown_seven_hundred_thirty_seven = 11;
	string unknown_seven_hundred_thirty_eight = 12;
}

message UnknownThreeHundredEightyEight {
	string unknown_seven_hundred = 1;
}

message UnknownThreeHundredEightyNine {
	UnknownThreeHundredSeventyThree unknown_seven_hundred_one = 1;
}

message UnknownThreeHundredNinety {
	UnknownThreeHundredSeventyFour unknown_seven_hundred_two = 1;
}

message UnknownThreeHundredNinetyOne {
	UnknownThreeHundredSeventyFive unknown_seven_hundred_three = 1;
	string unknown_seven_hundred_four = 2;
}

message UnknownThreeHundredNinetyTwo {
	string unknown_seven_hundred_five = 1;
	string unknown_seven_hundred_six = 2;
	repeated int32 unknown_seven_hundred_seven = 3;
}

message LobbyCreateRequest {
	repeated int32 unknown_six_hundred_eighty_three = 1;
	bool unknown_six_hundred_eighty_four = 2;
	int32 unknown_six_hundred_eighty_five = 3;
	string unknown_six_hundred_eighty_six = 4;
	int32 unknown_six_hundred_eighty_seven = 5;
	repeated int32 unknown_six_hundred_eighty_eight = 6;
	int32 unknown_six_hundred_eighty_nine = 7;
	bool unknown_six_hundred_ninety = 8;
	int32 unknown_six_hundred_ninety_one = 9;
}

message UnknownThreeHundredNinetyThree {
	string unknown_seven_hundred_eight = 1;
}

message UnknownThreeHundredNinetyFour {
	string unknown_seven_hundred_nine = 1;
}

message UnknownThreeHundredNinetySix {
	string unknown_seven_hundred_seventeen = 1;
}

message UnknownThreeHundredNinetySeven {
	string unknown_seven_hundred_eighteen = 1;
}

message UnknownThreeHundredNinetyEight {
	string unknown_seven_hundred_nineteen = 1;
	string unknown_seven_hundred_twenty = 2;
}

message UnknownThreeHundredNinetyNine {
	repeated string unknown_seven_hundred_twenty_one = 1;
}

message UnknownFourHundred {
	UnknownFourHundredOne unknown_seven_hundred_twenty_two = 1;
	enum UnknownFourHundredOne {
		UNKNOWN_FOUR_HUNDRED_ONE_UNSPECIFIED = 0;
		UNKNOWN_FOUR_HUNDRED_ONE_1 = 1;
		UNKNOWN_FOUR_HUNDRED_ONE_2 = 2;
		UNKNOWN_FOUR_HUNDRED_ONE_3 = 3;
		UNKNOWN_FOUR_HUNDRED_ONE_4 = 4;
		UNKNOWN_FOUR_HUNDRED_ONE_5 = 5;
	}
}

message UnknownFourHundredTwo {
	string unknown_seven_hundred_twenty_three = 1;
	bool unknown_seven_hundred_twenty_four = 2;
}

message LobbyCreateResponse {
	UnknownThreeHundredSeventySeven unknown_six_hundred_ninety_two = 1;
	string unknown_six_hundred_ninety_three = 2;
}

message UnknownFourHundredThree {
	string unknown_seven_hundred_twenty_five = 1;
	string unknown_seven_hundred_twenty_six = 2;
}

message UnknownFourHundredFive {
	repeated int32 unknown_seven_hundred_thirty_nine = 1;
	string unknown_seven_hundred_forty = 2;
	map<string, string> unknown_seven_hundred_forty_one = 3;
}

message UnknownFourHundredSix {
	UnknownThreeHundredSeventyEight unknown_seven_hundred_forty_two = 1;
	.com.ankama.dofus.server.game.protocol.lobby.UnknownFourHundredSix.UnknownFourHundredSeven unknown_seven_hundred_forty_three = 2;
	message UnknownFourHundredSeven {
	}
	message UnknownFourHundredEight {
	}
}

message UnknownFourHundredNine {
	UnknownThreeHundredSeventyNine unknown_seven_hundred_forty_four = 1;
}

message UnknownFourHundredTen {
	UnknownThreeHundredEighty unknown_seven_hundred_forty_five = 1;
}

message UnknownFourHundredEleven {
	.com.ankama.dofus.server.game.protocol.lobby.UnknownThreeHundredNinetyFive unknown_seven_hundred_forty_six = 1;
}

message UnknownFourHundredTwelve {
	.com.ankama.dofus.server.game.protocol.lobby.UnknownThreeHundredNinetyFive unknown_seven_hundred_forty_seven = 1;
	string unknown_seven_hundred_forty_eight = 2;
}

message UnknownFourHundredFourteen {
	.com.ankama.dofus.server.game.protocol.lobby.UnknownThreeHundredNinetyFive unknown_seven_hundred_fifty_two = 1;
}

message UnknownFourHundredSixteen {
	UnknownThreeHundredEightyOne unknown_seven_hundred_fifty_three = 1;
}

message LobbyAdvertisementListEvent {
	.com.ankama.dofus.server.game.protocol.lobby.LobbyAdvertisementListEvent.UnknownThreeHundredSeventy unknown_six_hundred_eighty_one = 1;
	UnknownThreeHundredEightyTwo unknown_six_hundred_eighty_two = 2;
	message UnknownThreeHundredSeventy {
		repeated .com.ankama.dofus.server.game.protocol.lobby.UnknownFourHundredFour unknown_six_hundred_seventy_nine = 1;
		repeated .com.ankama.dofus.server.game.protocol.lobby.UnknownThreeHundredEightySix unknown_six_hundred_eighty = 2;
	}
}

message UnknownFourHundredSeventeen {
	string unknown_seven_hundred_fifty_four = 1;
}

message LobbyAdvertisementListRequest {
}

message UnknownFourHundredFifteen {
}

message LobbyStopListeningRequest {
}

message LobbyStopListeningResponse {
}
