syntax = "proto3";

package com.ankama.dofus.server.game.protocol.map.cell.tag;

message ShowCellTagOwnerEvent {
	int64 owner_id = 1;
	int32 cell_id = 2;
}

message ShowCellTagRequest {
	int32 cell_id = 1;
	int32 tag_type = 2;
}

message ShowCellTagsEvent {
	map<int64, int32> tag_type_by_entity_id = 1;
	map<int32, int32> tag_type_by_cell_id = 2;
}

message UnknownFourHundredNineteen {
	int32 unknown_seven_hundred_fifty_seven = 1;
}

message UnknownFourHundredTwenty {
	int32 unknown_seven_hundred_fifty_eight = 1;
}
