# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: security_file_check.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'security_file_check.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19security_file_check.proto\x12\x39\x63om.ankama.dofus.server.game.protocol.security.file.check\"\xc9\x01\n\x1dUnknownFourHundredEightyEight\x12\x82\x01\n unknown_eight_hundred_forty_nine\x18\x01 \x01(\x0e\x32X.com.ankama.dofus.server.game.protocol.security.file.check.UnknownFourHundredEightySeven\x12#\n\x1bunknown_eight_hundred_fifty\x18\x02 \x01(\t\"\xcb\x01\n\x1cUnknownFourHundredEightyNine\x12\'\n\x1funknown_eight_hundred_fifty_one\x18\x02 \x01(\t\x12\x81\x01\n\x1funknown_eight_hundred_fifty_two\x18\x03 \x01(\x0e\x32X.com.ankama.dofus.server.game.protocol.security.file.check.UnknownFourHundredEightySeven\"E\n\x18UnknownFourHundredNinety\x12)\n!unknown_eight_hundred_fifty_three\x18\x01 \x01(\x08*{\n\x1dUnknownFourHundredEightySeven\x12\x31\n-UNKNOWN_FOUR_HUNDRED_EIGHTY_SEVEN_UNSPECIFIED\x10\x00\x12\'\n#UNKNOWN_FOUR_HUNDRED_EIGHTY_SEVEN_1\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'security_file_check_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UNKNOWNFOURHUNDREDEIGHTYSEVEN']._serialized_start=569
  _globals['_UNKNOWNFOURHUNDREDEIGHTYSEVEN']._serialized_end=692
  _globals['_UNKNOWNFOURHUNDREDEIGHTYEIGHT']._serialized_start=89
  _globals['_UNKNOWNFOURHUNDREDEIGHTYEIGHT']._serialized_end=290
  _globals['_UNKNOWNFOURHUNDREDEIGHTYNINE']._serialized_start=293
  _globals['_UNKNOWNFOURHUNDREDEIGHTYNINE']._serialized_end=496
  _globals['_UNKNOWNFOURHUNDREDNINETY']._serialized_start=498
  _globals['_UNKNOWNFOURHUNDREDNINETY']._serialized_end=567
# @@protoc_insertion_point(module_scope)
