from src.core.behaviors.storage.consts import ASTRUB_BANK_MAP

MULE_BANK_MAP_ID = ASTRUB_BANK_MAP
MULE_BANK_CHARACTER_IDS: set[int] = {23438098782}
MULE_BANK_CHARACTER_LOGIN: set[str] = set()


BOT_MINIMAL_KAMAS: int = 1_000_000
BOT_KAMA_LIMIT_TO_GIVE: int = 1_500_000
