from enum import IntFlag


class MapCapabilityFlag(IntFlag):
    ALLOW_CHALLENGE = 1
    ALLOW_AGGRESSION = 2
    ALLOW_TELEPORT_TO = 4
    ALLOW_TELEPORT_FROM = 8
    ALLOW_EXCHANGES_BETWEEN_PLAYERS = 16
    ALLOW_HUMAN_VENDOR = 32
    ALLOW_COLLECTOR = 64
    ALLOW_SOUL_CAPTURE = 128
    ALLOW_SOUL_SUMMON = 256
    ALLOW_TAVERN_REGEN = 512
    ALLOW_TOMB_MODE = 1024
    ALLOW_TELEPORT_EVERYWHERE = 2048
    ALLOW_FIGHT_CHALLENGES = 4096
    ALLOW_MONSTER_RESPAWN = 8192
    ALLOW_MONSTER_FIGHT = 16384
    ALLOW_MOUNT = 32768
    ALLOW_OBJECT_DISPOSAL = 65536
    ALLOW_UNDERWATER = 131072
    ALLOW_PVP_1V1 = 262144
    ALLOW_PVP_3V3 = 524288
    ALLOW_MONSTER_AGRESSION = 1048576


def does_allow_capability(m_flags: int, capability: MapCapabilityFlag) -> bool:
    return (m_flags & capability) != 0
