# generated by datamodel-codegen:
#   filename:  ItemsRoot.json
#   timestamp: 2024-10-06T18:04:36+00:00

from __future__ import annotations

from typing import List, TypedDict, Union

from typing_extensions import NotRequired


class MGameObject(TypedDict):
    m_FileID: int
    m_PathID: int


class MScript(TypedDict):
    m_FileID: int
    m_PathID: int


class MKeys(TypedDict):
    Array: List[int]


class ArrayItem(TypedDict):
    rid: int


class MValues(TypedDict):
    Array: List[ArrayItem]


class ObjectsById(TypedDict):
    m_keys: MKeys
    m_values: MValues


Type = TypedDict(
    'Type',
    {
        'class': str,
        'ns': str,
        'asm': str,
    },
)


class RecipeIds(TypedDict):
    Array: List[int]


class DropMonsterIds(TypedDict):
    Array: List[int]


class DropTemporisMonsterIds(TypedDict):
    Array: List


class PossibleEffects(TypedDict):
    Array: List[ArrayItem]


class EvolutiveEffectIds(TypedDict):
    Array: List[int]


class FavoriteSubAreas(TypedDict):
    Array: List


class FavoriteRecyclingSubareas(TypedDict):
    Array: List[int]


class Values(TypedDict):
    Array: List[int]


class ArrayItem2(TypedDict):
    values: Values


class ResourcesBySubarea(TypedDict):
    Array: List[ArrayItem2]


class CellIds(TypedDict):
    Array: List


class ZoneDescr(TypedDict):
    cellIds: CellIds
    shape: int
    param1: int
    param2: int
    damageDecreaseStepPercent: int
    maxDamageDecreaseApplyCount: int
    isStopAtTarget: int


class Data(TypedDict):
    m_flags: int
    id: NotRequired[int]
    nameId: NotRequired[int]
    typeId: NotRequired[int]
    descriptionId: NotRequired[int]
    iconId: NotRequired[int]
    level: NotRequired[int]
    realWeight: NotRequired[int]
    useAnimationId: NotRequired[int]
    price: NotRequired[float]
    itemSetId: NotRequired[int]
    criteria: NotRequired[str]
    criteriaTarget: NotRequired[str]
    appearanceId: NotRequired[int]
    isColorable: NotRequired[int]
    recipeSlots: NotRequired[int]
    recipeIds: NotRequired[RecipeIds]
    dropMonsterIds: NotRequired[DropMonsterIds]
    dropTemporisMonsterIds: NotRequired[DropTemporisMonsterIds]
    possibleEffects: NotRequired[PossibleEffects]
    evolutiveEffectIds: NotRequired[EvolutiveEffectIds]
    favoriteSubAreas: NotRequired[FavoriteSubAreas]
    favoriteSubAreasBonus: NotRequired[int]
    craftXpRatio: NotRequired[int]
    craftVisible: NotRequired[str]
    craftConditional: NotRequired[str]
    craftFeasible: NotRequired[str]
    visibility: NotRequired[str]
    recyclingNuggets: NotRequired[float]
    favoriteRecyclingSubareas: NotRequired[FavoriteRecyclingSubareas]
    resourcesBySubarea: NotRequired[ResourcesBySubarea]
    importantNoticeId: NotRequired[str]
    changeVersion: NotRequired[str]
    tooltipExpirationDate: NotRequired[Union[float, str]]
    criticalFailureProbability: NotRequired[int]
    criticalHitBonus: NotRequired[int]
    minRange: NotRequired[int]
    criticalHitProbability: NotRequired[int]
    range: NotRequired[int]
    castInLine: NotRequired[int]
    apCost: NotRequired[int]
    castInDiagonal: NotRequired[int]
    castTestLos: NotRequired[int]
    maxCastPerTurn: NotRequired[int]
    effectUid: NotRequired[int]
    baseEffectId: NotRequired[int]
    effectId: NotRequired[int]
    order: NotRequired[int]
    targetId: NotRequired[int]
    targetMask: NotRequired[str]
    duration: NotRequired[int]
    random: NotRequired[float]
    group: NotRequired[int]
    modificator: NotRequired[int]
    dispellable: NotRequired[int]
    delay: NotRequired[int]
    triggers: NotRequired[str]
    effectElement: NotRequired[int]
    spellId: NotRequired[int]
    effectTriggerDuration: NotRequired[int]
    zoneDescr: NotRequired[ZoneDescr]
    value: NotRequired[int]
    diceNum: NotRequired[int]
    diceSide: NotRequired[int]
    displayZero: NotRequired[int]


class RefId(TypedDict):
    rid: int
    type: Type
    data: Data


class References(TypedDict):
    version: int
    RefIds: List[RefId]


class Model(TypedDict):
    m_GameObject: MGameObject
    m_Enabled: int
    m_Script: MScript
    m_Name: str
    objectsById: ObjectsById
    references: References
