# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/ankama/dofus/server/game/protocol/dialog.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'com/ankama/dofus/server/game/protocol/dialog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.ankama.dofus.server.game.protocol import common_pb2 as com_dot_ankama_dot_dofus_dot_server_dot_game_dot_protocol_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2com/ankama/dofus/server/game/protocol/dialog.proto\x12,com.ankama.dofus.server.game.protocol.dialog\x1a\x32\x63om/ankama/dofus/server/game/protocol/common.proto\"\x14\n\x12\x44ialogLeaveRequest\"a\n\x10\x44ialogLeaveEvent\x12M\n\x0b\x64ialog_type\x18\x01 \x01(\x0e\x32\x38.com.ankama.dofus.server.game.protocol.common.DialogTypeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.ankama.dofus.server.game.protocol.dialog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DIALOGLEAVEREQUEST']._serialized_start=152
  _globals['_DIALOGLEAVEREQUEST']._serialized_end=172
  _globals['_DIALOGLEAVEEVENT']._serialized_start=174
  _globals['_DIALOGLEAVEEVENT']._serialized_end=271
# @@protoc_insertion_point(module_scope)
