from typing import Any

from PyQt6.QtWidgets import QHBoxLayout, QWidget

from qfluentwidgets import FluentTitleBar
from qfluentwidgets.window.stacked_widget import StackedWidget

class FluentWindowBase(QWidget):
    hBoxLayout: QHBoxLayout
    titleBar: FluentTitleBar
    stackedWidget: StackedWidget
    def __init__(self, parent: QWidget | None = None) -> None: ...
    def setTitleBar(self, titleBar: Any) -> None: ...
    def _updateStackedBackground(self) -> None: ...
    def switchTo(self, widget: QWidget) -> None: ...
    def _onCurrentInterfaceChanged(self, index: int) -> None: ...
