from PyQt6.QtCore import pyqtSignal
from PyQt6.QtWidgets import QFrame, QWidget

class _PopUpAniStackedWidget(QWidget):
    currentChanged: pyqtSignal
    def setCurrentWidget(self, widget: QWidget, *, duration: int = 300) -> None: ...
    def currentIndex(self) -> int: ...
    def currentWidget(self) -> QWidget | None: ...
    def indexOf(self, widget: QWidget) -> int: ...
    def count(self) -> int: ...
    def widget(self, index: int) -> QWidget | None: ...
    def addWidget(self, widget: QWidget) -> None: ...
    def removeWidget(self, widget: QWidget) -> None: ...
    def isAnimationEnabled(self) -> bool: ...
    def setAnimationEnabled(self, isEnabled: bool) -> None: ...

class StackedWidget(QFrame):
    currentChanged: pyqtSignal
    view: _PopUpAniStackedWidget
    def __init__(self, parent: QWidget | None = None) -> None: ...
    def addWidget(self, widget: QWidget) -> None: ...
    def removeWidget(self, widget: QWidget) -> None: ...
    def widget(self, index: int) -> QWidget | None: ...
    def setCurrentWidget(self, widget: QWidget, popOut: bool = True) -> None: ...
    def setCurrentIndex(self, index: int, popOut: bool = True) -> None: ...
    def currentIndex(self) -> int: ...
    def currentWidget(self) -> QWidget | None: ...
    def indexOf(self, widget: QWidget) -> int: ...
    def count(self) -> int: ...
    def isAnimationEnabled(self) -> bool: ...
    def setAnimationEnabled(self, isEnabled: bool) -> None: ...
