// Copyright © 2024-2026 Xpl0itR
// 
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using ConsoleAppFramework;
using LibProtodec;
using LibProtodec.Deobfuscation;
using LibProtodec.Loaders;
using LibProtodec.Models.Protobuf;
using LibProtodec.Reflection;
using LibProtodec.Reflection.Clr;
using LibProtodec.Reflection.Il2Cpp;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

ConsoleApp.ConsoleAppBuilder app = ConsoleApp.Create();
app.Add<Commands>();
app.Run(args);

internal sealed class Commands
{
    /// <summary>
    ///     Derive Protobuf schemas by reflecting target CIL assembly and its dependencies to parse classes generated by protoc with the "csharp_out" option.
    /// </summary>
    /// <param name="targetPath">Either the path to the target assembly or a directory of assemblies, all of which be loaded for reflection.</param>
    /// <param name="outPath">An existing directory to output into individual files, otherwise output to a single file.</param>
    /// <param name="targetAssemblyName">Override/Specify the name of the assembly to parse.</param>
    /// <param name="parseServiceServers">Parses gRPC service definitions from server classes.</param>
    /// <param name="parseServiceClients">Parses gRPC service definitions from client classes.</param>
    /// <param name="skipEnums">Skip parsing enums and replace references to them with int32.</param>
    /// <param name="includePropertiesWithoutNonUserCodeAttribute">Includes properties that aren't decorated with `DebuggerNonUserCode` when parsing.</param>
    /// <param name="includeServiceMethodsWithoutGeneratedCodeAttribute">Includes methods that aren't decorated with `GeneratedCode("grpc_csharp_plugin")` when parsing gRPC services.</param>
    /// <param name="requireGeneratedCodeAttributeForProperties">Requires properties to be decorated with `GeneratedCode("protoc")` to be parsed.</param>
    /// <param name="logLevel">Logging severity level.</param>
    [Command("")]
    public void Root(
        [Argument] string targetPath,
        [Argument] string outPath,
        string?           targetAssemblyName                                 = null,
        bool              parseServiceServers                                = false,
        bool              parseServiceClients                                = false,
        bool              skipEnums                                          = false,
        bool              includePropertiesWithoutNonUserCodeAttribute       = false,
        bool              includeServiceMethodsWithoutGeneratedCodeAttribute = false,
        bool              requireGeneratedCodeAttributeForProperties         = false,
        LogLevel          logLevel                                           = LogLevel.Information)
    {
        ILoggerFactory loggerFactory = SetupLogging(logLevel, out ILogger logger);

        logger.LogInformation("Loading CIL assemblies...");
        using MlcAssemblyLoader loader = new(targetPath, targetAssemblyName, loggerFactory.CreateLogger<MlcAssemblyLoader>());

        HandleCil(
            loader,
            outPath,
            parseServiceServers,
            parseServiceClients,
            skipEnums,
            includePropertiesWithoutNonUserCodeAttribute,
            includeServiceMethodsWithoutGeneratedCodeAttribute,
            requireGeneratedCodeAttributeForProperties,
            loggerFactory,
            logger);
    }

    /// <summary>
    ///     Derive Protobuf schemas by reflecting target IL2CPP compiled assembly to parse classes generated by protoc with the "csharp_out" option.
    /// </summary>
    /// <param name="gameAssembly">The path to the game assembly DLL.</param>
    /// <param name="globalMetadata">The path to the global-metadata.dat file.</param>
    /// <param name="unityVersion">The version of Unity which was used to create the metadata file or alternatively, the path to the globalgamemanagers or the data.unity3d file.</param>
    /// <param name="outPath">An existing directory to output into individual files, otherwise output to a single file.</param>
    /// <param name="parseServiceServers">Parses gRPC service definitions from server classes.</param>
    /// <param name="parseServiceClients">Parses gRPC service definitions from client classes.</param>
    /// <param name="skipEnums">Skip parsing enums and replace references to them with int32.</param>
    /// <param name="includePropertiesWithoutNonUserCodeAttribute">Includes properties that aren't decorated with `DebuggerNonUserCode` when parsing.</param>
    /// <param name="includeServiceMethodsWithoutGeneratedCodeAttribute">Includes methods that aren't decorated with `GeneratedCode("grpc_csharp_plugin")` when parsing gRPC services.</param>
    /// <param name="requireGeneratedCodeAttributeForProperties">Requires properties to be decorated with `GeneratedCode("protoc")` to be parsed.</param>
    /// <param name="logLevel">Logging severity level.</param>
    [Command("il2cpp")]
    public void Il2Cpp(
        [Argument] string gameAssembly,
        [Argument] string globalMetadata,
        [Argument] string unityVersion,
        [Argument] string outPath,
        bool              parseServiceServers                                = false,
        bool              parseServiceClients                                = false,
        bool              skipEnums                                          = false,
        bool              includePropertiesWithoutNonUserCodeAttribute       = false,
        bool              includeServiceMethodsWithoutGeneratedCodeAttribute = false,
        bool              requireGeneratedCodeAttributeForProperties         = false,
        LogLevel          logLevel                                           = LogLevel.Information)
    {
        ILoggerFactory loggerFactory = SetupLogging(logLevel, out ILogger logger);

        logger.LogInformation("Loading IL2CPP assembly and metadata files...");
        using Il2CppAssemblyLoader loader = Il2CppAssemblyLoader.LoadFromFiles(gameAssembly, globalMetadata, unityVersion, loggerFactory);

        if (loader.Metadata.MetadataVersion < 29f)
        {
            logger.LogWarning("Detected IL2CPP version less than 29. For possibly better decompilation results, it is recommended to instead use assemblies generated by the \"new-analysis\" branch of Cpp2IL.");
        }

        HandleCil(
            loader,
            outPath,
            parseServiceServers,
            parseServiceClients,
            skipEnums,
            includePropertiesWithoutNonUserCodeAttribute,
            includeServiceMethodsWithoutGeneratedCodeAttribute,
            requireGeneratedCodeAttributeForProperties,
            loggerFactory,
            logger);
    }

    private static void HandleCil(
        ICilAssemblyLoader loader,
        string             outPath,
        bool               parseServiceServers,
        bool               parseServiceClients,
        bool               skipEnums,
        bool               includePropertiesWithoutNonUserCodeAttribute,
        bool               includeServiceMethodsWithoutGeneratedCodeAttribute,
        bool               requireGeneratedCodeAttributeForProperties,
        ILoggerFactory     loggerFactory,
        ILogger            logger)
    {
        CilParserOptions options = CilParserOptions.None;
        if (skipEnums)
            options |= CilParserOptions.SkipEnums;
        if (includePropertiesWithoutNonUserCodeAttribute)
            options |= CilParserOptions.IncludePropertiesWithoutNonUserCodeAttribute;
        if (includeServiceMethodsWithoutGeneratedCodeAttribute)
            options |= CilParserOptions.IncludeServiceMethodsWithoutGeneratedCodeAttribute;
        if (requireGeneratedCodeAttributeForProperties)
            options |= CilParserOptions.RequireGeneratedCodeAttributeForProperties;

        ProtodecContext ctx = new()
        {
            Logger         = loggerFactory.CreateLogger<ProtodecContext>(),
            NameTranslator = new BeebyteNameTranslator(new Dictionary<string, string>()) // replicates default behaviour from previous versions
        };

        logger.LogInformation("Parsing Protobuf message types...");
        foreach (ICilType message in loader.GetProtobufMessageTypes())
        {
            ctx.ParseMessage(message, options);
        }

        if (parseServiceServers)
        {
            logger.LogInformation("Parsing Protobuf service server types...");
            foreach (ICilType service in loader.GetProtobufServiceServerTypes())
            {
                ctx.ParseService(service, options);
            }
        }

        if (parseServiceClients)
        {
            logger.LogInformation("Parsing Protobuf service client types...");
            foreach (ICilType service in loader.GetProtobufServiceClientTypes())
            {
                ctx.ParseService(service, options);
            }
        }

        WriteProtobufs(ctx, outPath, logger);
    }

    private static void WriteProtobufs(ProtodecContext ctx, string outPath, ILogger logger)
    {
        const string indent = "  ";
        if (Directory.Exists(outPath))
        {
            logger.LogInformation("Writing {count} Protobuf schema files to \"{path}\"...", ctx.Protobufs.Count, outPath);

            HashSet<string> writtenFiles = [];
            foreach (Protobuf protobuf in ctx.Protobufs)
            {
                // This workaround stops files from being overwritten in the case of a naming conflict,
                // however the actual conflict will still have to be resolved manually
                string fileName = protobuf.FileName;
                while (!writtenFiles.Add(fileName))
                {
                    fileName = '_' + fileName;
                }

                string protobufPath = Path.Join(outPath, fileName);

                using StreamWriter       streamWriter = new(protobufPath);
                using IndentedTextWriter indentWriter = new(streamWriter, indent);

                protobuf.WriteTo(indentWriter);
            }
        }
        else
        {
            logger.LogInformation("Writing Protobufs as a single file to \"{path}\"...", outPath);

            using StreamWriter       streamWriter = new(outPath);
            using IndentedTextWriter indentWriter = new(streamWriter, indent);

            ctx.WriteAllTo(indentWriter);
        }
    }

    private static ILoggerFactory SetupLogging(LogLevel logLevel, out ILogger programLogger)
    {
        ServiceCollection services = new();
        services.AddLogging(builder =>
            builder.SetMinimumLevel(logLevel)
                   .AddSimpleConsole(static console => console.IncludeScopes = true));

        IServiceProvider sp = ConsoleApp.ServiceProvider = services.BuildServiceProvider();
        ILoggerFactory loggerFactory = sp.GetRequiredService<ILoggerFactory>();

        ILogger logger = programLogger = loggerFactory.CreateLogger("protodec");
        ConsoleApp.LogError = error => logger.Log(LogLevel.Critical, 0, error, null, static (msg, _) => msg);

        return loggerFactory;
    }
}