# generated by datamodel-codegen:
#   filename:  AchievementProgressStepsRoot.json
#   timestamp: 2025-06-08T12:27:36+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class AchievementprogressstepsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    progressId: int
    score: int
    isCosmetic: int
    achievementId: int
    isBuyable: int


Achievementprogressstepsroot = List[AchievementprogressstepsrootItem]
