# generated by datamodel-codegen:
#   filename:  AchievementObjectivesRoot.json
#   timestamp: 2025-06-08T12:27:30+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class AchievementobjectivesrootItem(Struct, frozen=True, kw_only=True):
    id: int
    achievementId: int
    order: int
    nameId: int
    criterion: str


Achievementobjectivesroot = List[AchievementobjectivesrootItem]
