# generated by datamodel-codegen:
#   filename:  AchievementCategoriesRoot.json
#   timestamp: 2025-06-08T12:27:26+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class AchievementcategoriesrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int
    parentId: int
    icon: str
    order: int
    color: str
    achievementIds: List[int]
    visibilityCriterion: str


Achievementcategoriesroot = List[AchievementcategoriesrootItem]
