# generated by datamodel-codegen:
#   filename:  AchievementProgressRoot.json
#   timestamp: 2025-06-08T12:27:33+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class AchievementprogressrootItem(Struct, frozen=True, kw_only=True):
    id: int
    name: str
    seasonId: int


Achievementprogressroot = List[AchievementprogressrootItem]
