# generated by datamodel-codegen:
#   filename:  AlignmentGiftRoot.json
#   timestamp: 2025-06-08T12:27:56+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class AlignmentgiftrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int


Alignmentgiftroot = List[AlignmentgiftrootItem]
