# generated by datamodel-codegen:
#   filename:  AlignmentRankRoot.json
#   timestamp: 2025-06-08T12:28:05+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class AlignmentrankrootItem(Struct, frozen=True, kw_only=True):
    id: int
    orderId: int
    nameId: int
    descriptionId: int
    minimumAlignment: int


Alignmentrankroot = List[AlignmentrankrootItem]
