# generated by datamodel-codegen:
#   filename:  AlignmentOrderRoot.json
#   timestamp: 2025-06-08T12:27:59+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class AlignmentorderrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int
    sideId: int


Alignmentorderroot = List[AlignmentorderrootItem]
