# generated by datamodel-codegen:
#   filename:  AlmanaxCalendarsRoot.json
#   timestamp: 2025-06-08T12:28:33+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class AlmanaxcalendarsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int
    descId: str
    npcId: int
    bonusesIds: List[int]


Almanaxcalendarsroot = List[AlmanaxcalendarsrootItem]
