# generated by datamodel-codegen:
#   filename:  AppearancesRoot.json
#   timestamp: 2025-06-08T12:28:42+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class AppearancesrootItem(Struct, frozen=True, kw_only=True):
    id: int
    type: int
    data: str


Appearancesroot = List[AppearancesrootItem]
