# generated by datamodel-codegen:
#   filename:  ArenaLeagueRewardsRoot.json
#   timestamp: 2025-06-08T12:28:45+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class ArenaleaguerewardsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    seasonId: int
    leagueId: int
    titlesRewards: List[int]
    endSeasonRewards: int


Arenaleaguerewardsroot = List[ArenaleaguerewardsrootItem]
