# generated by datamodel-codegen:
#   filename:  ArenaLeaguesRoot.json
#   timestamp: 2025-06-08T12:28:51+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class ArenaleaguesrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int
    ornamentId: int
    icon: str
    illus: str
    isLastLeague: int
    lowRatingBound: int
    highRatingBound: int


Arenaleaguesroot = List[ArenaleaguesrootItem]
