# generated by datamodel-codegen:
#   filename:  BonusesRoot.json
#   timestamp: 2025-06-08T12:28:58+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class BonusesrootItem(Struct, frozen=True, kw_only=True):
    id: int
    type: int
    amount: int
    criterionsIds: List[int]


Bonusesroot = List[BonusesrootItem]
