# generated by datamodel-codegen:
#   filename:  BreachWorldMapSectorsRoot.json
#   timestamp: 2025-06-08T12:29:16+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class BreachworldmapsectorsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    sectorNameId: str
    legendId: str
    sectorIcon: str
    minStage: int
    maxStage: int


Breachworldmapsectorsroot = List[BreachworldmapsectorsrootItem]
