# generated by datamodel-codegen:
#   filename:  BreachInfinityLevelsRoot.json
#   timestamp: 2025-06-08T12:29:07+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class BreachinfinitylevelsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int
    level: int


Breachinfinitylevelsroot = List[BreachinfinitylevelsrootItem]
