# generated by datamodel-codegen:
#   filename:  CensoredContentsRoot.json
#   timestamp: 2025-06-08T12:29:25+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class CensoredcontentsrootItem(Struct, frozen=True, kw_only=True):
    lang: str
    type: int
    oldValue: int
    newValue: int


Censoredcontentsroot = List[CensoredcontentsrootItem]
