# generated by datamodel-codegen:
#   filename:  CollectionsRoot.json
#   timestamp: 2025-06-08T12:29:47+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class Collectable(Struct, frozen=True, kw_only=True):
    entityId: int
    name: str
    typeId: int
    gfxId: int
    order: int
    rarity: int


class CollectionsrootItem(Struct, frozen=True, kw_only=True):
    typeId: int
    name: str
    criterion: str
    collectables: List[Collectable]


Collectionsroot = List[CollectionsrootItem]
