# generated by datamodel-codegen:
#   filename:  CustomModeBreedSpellsRoot.json
#   timestamp: 2025-06-08T12:30:06+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class CustommodebreedspellsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    pairId: int
    breedId: int
    isInitialSpell: int
    isHidden: int


Custommodebreedspellsroot = List[CustommodebreedspellsrootItem]
