# generated by datamodel-codegen:
#   filename:  DocumentsRoot.json
#   timestamp: 2025-06-08T12:30:09+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class DocumentsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    typeId: int
    showTitle: int
    showBackgroundImage: int
    titleId: str
    authorId: str
    subTitleId: str
    contentId: str
    contentCSS: str
    clientProperties: str


Documentsroot = List[DocumentsrootItem]
