# generated by datamodel-codegen:
#   filename:  EmblemBackgroundsRoot.json
#   timestamp: 2025-06-08T12:30:13+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class EmblembackgroundsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    order: int


Emblembackgroundsroot = List[EmblembackgroundsrootItem]
