# generated by datamodel-codegen:
#   filename:  EmblemSymbolsRoot.json
#   timestamp: 2025-06-08T12:30:19+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class EmblemsymbolsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    skinId: int
    iconId: int
    order: int
    categoryId: int
    colorizable: int


Emblemsymbolsroot = List[EmblemsymbolsrootItem]
