# generated by datamodel-codegen:
#   filename:  EmoticonsRoot.json
#   timestamp: 2025-06-08T12:30:22+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class EmoticonsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int
    shortcutId: str
    order: int
    animName: str
    persistancy: int
    persistantAnimName: str
    eightDirections: int
    aura: int
    cooldown: int
    duration: int
    weight: int
    spellLevelId: int
    scale: int


Emoticonsroot = List[EmoticonsrootItem]
