# generated by datamodel-codegen:
#   filename:  ExpeditionSeasonsRoot.json
#   timestamp: 2025-06-08T12:30:31+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class ExpeditionseasonsrootItem(Struct, frozen=True, kw_only=True):
    uid: int
    nameId: str
    beginning: float
    closure: float
    resetDate: float
    flagObjectId: int


Expeditionseasonsroot = List[ExpeditionseasonsrootItem]
