# generated by datamodel-codegen:
#   filename:  FightScenariosRoot.json
#   timestamp: 2025-06-08T12:30:40+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class FightscenariosrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: str


Fightscenariosroot = List[FightscenariosrootItem]
