# generated by datamodel-codegen:
#   filename:  ForgettableSpellsRoot.json
#   timestamp: 2025-06-08T12:30:46+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class ForgettablespellsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    pairId: int
    itemId: int


Forgettablespellsroot = List[ForgettablespellsrootItem]
