# generated by datamodel-codegen:
#   filename:  GuildChestTabsRoot.json
#   timestamp: 2025-06-08T12:30:49+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class GuildchesttabsrootItem(Struct, frozen=True, kw_only=True):
    tabId: int
    nameId: int
    index: int
    gfxId: int
    serverType: int
    cost: int
    seniority: int
    openRight: int
    dropRight: int
    takeRight: int


Guildchesttabsroot = List[GuildchesttabsrootItem]
