# generated by datamodel-codegen:
#   filename:  GuildRightGroupsRoot.json
#   timestamp: 2025-06-08T12:30:59+00:00

from __future__ import annotations

from typing import List, Optional

from msgspec import Struct


class Right(Struct, frozen=True, kw_only=True):
    rid: int


class GuildrightgroupsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int
    order: int
    rights: Optional[List[Right]] = None
    groupId: Optional[int] = None


Guildrightgroupsroot = List[GuildrightgroupsrootItem]
