# generated by datamodel-codegen:
#   filename:  GuildRankNameSuggestionsRoot.json
#   timestamp: 2025-06-08T12:30:52+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class GuildranknamesuggestionsrootItem(Struct, frozen=True, kw_only=True):
    uiKey: str


Guildranknamesuggestionsroot = List[GuildranknamesuggestionsrootItem]
