# generated by datamodel-codegen:
#   filename:  GuildTagsTypesRoot.json
#   timestamp: 2025-06-08T12:31:08+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class GuildtagstypesrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int


Guildtagstypesroot = List[GuildtagstypesrootItem]
