# generated by datamodel-codegen:
#   filename:  GuildRightsRoot.json
#   timestamp: 2025-06-08T12:31:02+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class GuildrightsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int
    order: int
    groupId: int


Guildrightsroot = List[GuildrightsrootItem]
