# generated by datamodel-codegen:
#   filename:  HavenbagThemesRoot.json
#   timestamp: 2025-06-08T12:31:14+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class HavenbagthemesrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int
    mapId: int


Havenbagthemesroot = List[HavenbagthemesrootItem]
