# generated by datamodel-codegen:
#   filename:  HeadsRoot.json
#   timestamp: 2025-06-08T12:31:17+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class HeadsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    skins: str
    assetId: str
    breed: int
    gender: int
    label: str
    order: int
    payable: int


Headsroot = List[HeadsrootItem]
