# generated by datamodel-codegen:
#   filename:  HintCategoryRoot.json
#   timestamp: 2025-06-08T12:31:21+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class HintcategoryrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int


Hintcategoryroot = List[HintcategoryrootItem]
