# generated by datamodel-codegen:
#   filename:  HousesRoot.json
#   timestamp: 2025-06-08T12:31:27+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class HousesrootItem(Struct, frozen=True, kw_only=True):
    typeId: int
    defaultPrice: int
    nameId: int
    descriptionId: int
    gfxId: int
    roomCount: int


Housesroot = List[HousesrootItem]
