# generated by datamodel-codegen:
#   filename:  IncarnationLevelsRoot.json
#   timestamp: 2025-06-08T12:31:30+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class IncarnationlevelsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    incarnationId: int
    level: int
    requiredXp: int


Incarnationlevelsroot = List[IncarnationlevelsrootItem]
