# generated by datamodel-codegen:
#   filename:  InteractivesRoot.json
#   timestamp: 2025-06-08T12:31:39+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class InteractivesrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int
    actionId: int
    displayTooltip: int


Interactivesroot = List[InteractivesrootItem]
