# generated by datamodel-codegen:
#   filename:  ItemSuperTypesRoot.json
#   timestamp: 2025-06-08T12:31:53+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class ItemsupertypesrootItem(Struct, frozen=True, kw_only=True):
    id: int
    possiblePositions: List[int]


Itemsupertypesroot = List[ItemsupertypesrootItem]
