# generated by datamodel-codegen:
#   filename:  LegendaryPowersCategoriesRoot.json
#   timestamp: 2025-06-08T12:32:00+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class LegendarypowerscategoriesrootItem(Struct, frozen=True, kw_only=True):
    id: int
    categoryName: str
    categoryOverridable: int
    categorySpells: List[int]


Legendarypowerscategoriesroot = List[LegendarypowerscategoriesrootItem]
