# generated by datamodel-codegen:
#   filename:  MapPositionsRoot.json
#   timestamp: 2024-11-23T10:42:03+00:00

from __future__ import annotations

from msgspec import Struct


class MapInformationRootItem(Struct, frozen=True, kw_only=True):
    m_flags: int
    id: int
    posX: int
    posY: int
    nameId: int
    subAreaId: int
    worldMap: int
    tacticalModeTemplateId: int

    def __hash__(self):
        return self.id.__hash__()


MapInformationsRoot = list[MapInformationRootItem]
