# generated by datamodel-codegen:
#   filename:  MapReferencesRoot.json
#   timestamp: 2025-06-08T12:32:17+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class MapreferencesrootItem(Struct, frozen=True, kw_only=True):
    id: int
    mapId: int
    cellId: int


Mapreferencesroot = List[MapreferencesrootItem]
