# generated by datamodel-codegen:
#   filename:  MapScrollActionsRoot.json
#   timestamp: 2025-06-08T12:32:20+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class MapscrollactionsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    rightExists: int
    bottomExists: int
    leftExists: int
    topExists: int
    rightMapId: int
    bottomMapId: int
    leftMapId: int
    topMapId: int


Mapscrollactionsroot = List[MapscrollactionsrootItem]
