# generated by datamodel-codegen:
#   filename:  MonsterSuperRacesRoot.json
#   timestamp: 2025-06-08T12:32:38+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class MonstersuperracesrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int


Monstersuperracesroot = List[MonstersuperracesrootItem]
