# generated by datamodel-codegen:
#   filename:  MonsterMiniBossRoot.json
#   timestamp: 2025-06-08T12:32:26+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class MonsterminibossrootItem(Struct, frozen=True, kw_only=True):
    id: int
    monsterReplacingId: int


Monsterminibossroot = List[MonsterminibossrootItem]
