# generated by datamodel-codegen:
#   filename:  MonsterRacesRoot.json
#   timestamp: 2025-06-08T12:32:29+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class MonsterracesrootItem(Struct, frozen=True, kw_only=True):
    id: int
    superRaceId: int
    nameId: int
    aggressiveZoneSize: int
    aggressiveLevelDiff: int
    aggressiveImmunityCriterion: str
    aggressiveAttackDelay: int
    monsters: List[int]


Monsterracesroot = List[MonsterracesrootItem]
