# generated by datamodel-codegen:
#   filename:  MountFamilyRoot.json
#   timestamp: 2025-06-08T12:32:50+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class MountfamilyrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int
    headUri: str


Mountfamilyroot = List[MountfamilyrootItem]
