# generated by datamodel-codegen:
#   filename:  MountBehaviorsRoot.json
#   timestamp: 2025-06-08T12:32:44+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class MountbehaviorsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int
    descriptionId: int


Mountbehaviorsroot = List[MountbehaviorsrootItem]
