# generated by datamodel-codegen:
#   filename:  MountsRoot.json
#   timestamp: 2025-06-08T12:32:54+00:00

from __future__ import annotations

from typing import List, Optional

from msgspec import Struct


class Effect(Struct, frozen=True, kw_only=True):
    rid: int


class ZoneDescr(Struct, frozen=True, kw_only=True):
    cellIds: List
    shape: int
    param1: int
    param2: int
    damageDecreaseStepPercent: int
    maxDamageDecreaseApplyCount: int
    isStopAtTarget: int


class MountsrootItem(Struct, frozen=True, kw_only=True):
    id: Optional[int] = None
    familyId: Optional[int] = None
    nameId: Optional[int] = None
    look: Optional[str] = None
    certificateId: Optional[int] = None
    effects: Optional[List[Effect]] = None
    m_flags: Optional[int] = None
    effectUid: Optional[int] = None
    baseEffectId: Optional[int] = None
    effectId: Optional[int] = None
    order: Optional[int] = None
    targetId: Optional[int] = None
    targetMask: Optional[str] = None
    duration: Optional[int] = None
    random: Optional[float] = None
    group: Optional[int] = None
    modificator: Optional[int] = None
    dispellable: Optional[int] = None
    delay: Optional[int] = None
    triggers: Optional[str] = None
    effectElement: Optional[int] = None
    spellId: Optional[int] = None
    effectTriggerDuration: Optional[int] = None
    zoneDescr: Optional[ZoneDescr] = None
    value: Optional[int] = None
    diceNum: Optional[int] = None
    diceSide: Optional[int] = None
    displayZero: Optional[int] = None


Mountsroot = List[MountsrootItem]
