# generated by datamodel-codegen:
#   filename:  NotificationsRoot.json
#   timestamp: 2025-06-08T12:33:00+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class NotificationsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    titleId: str
    messageId: str
    iconId: int
    typeId: int
    trigger: str
    cantBeClosed: int


Notificationsroot = List[NotificationsrootItem]
