# generated by datamodel-codegen:
#   filename:  OptionalFeaturesRoot.json
#   timestamp: 2025-06-08T12:33:10+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class OptionalfeaturesrootItem(Struct, frozen=True, kw_only=True):
    id: int
    keyword: str
    isClient: int
    isServer: int
    isActivationOnLaunch: int
    isActivationOnServerConnection: int
    activationCriterions: str


Optionalfeaturesroot = List[OptionalfeaturesrootItem]
