# generated by datamodel-codegen:
#   filename:  OrnamentsRoot.json
#   timestamp: 2025-06-08T12:33:13+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class OrnamentsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int
    visible: int
    assetId: int
    iconId: int
    order: int


Ornamentsroot = List[OrnamentsrootItem]
