# generated by datamodel-codegen:
#   filename:  PointOfInterestRoot.json
#   timestamp: 2025-06-08T12:33:25+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class PointofinterestrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int
    categoryId: int


Pointofinterestroot = List[PointofinterestrootItem]
