# generated by datamodel-codegen:
#   filename:  PointOfInterestCategoryRoot.json
#   timestamp: 2025-06-08T12:33:22+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class PointofinterestcategoryrootItem(Struct, frozen=True, kw_only=True):
    id: int


Pointofinterestcategoryroot = List[PointofinterestcategoryrootItem]
