# generated by datamodel-codegen:
#   filename:  PopupInformationsRoot.json
#   timestamp: 2025-06-08T12:33:28+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class Button(Struct, frozen=True, kw_only=True):
    id: int
    popupId: int
    type: int
    textId: str
    actionType: int
    actionValue: str


class PopupinformationsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    parentId: int
    titleId: str
    descriptionId: int
    illuName: str
    buttons: List[Button]
    criterion: str
    cacheType: int
    autoTrigger: int


Popupinformationsroot = List[PopupinformationsrootItem]
