# generated by datamodel-codegen:
#   filename:  QuestCategoryRoot.json
#   timestamp: 2025-06-08T12:33:34+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class QuestcategoryrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int
    order: int
    questIds: List[int]


Questcategoryroot = List[QuestcategoryrootItem]
