# generated by datamodel-codegen:
#   filename:  QuestsRoot.json
#   timestamp: 2024-11-23T10:42:09+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class QuestsRootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int
    categoryId: int
    repeatType: int
    repeatLimit: int
    isDungeonQuest: int
    levelMin: int
    levelMax: int
    stepIds: List[int]
    isPartyQuest: int
    startCriterion: str
    followable: int
    isEvent: int

    def __hash__(self):
        return self.id.__hash__()


QuestsRoot = list[QuestsRootItem]
