# generated by datamodel-codegen:
#   filename:  QuestStepsRoot.json
#   timestamp: 2025-06-08T12:33:46+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class QueststepsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    questId: int
    nameId: int
    descriptionId: int
    dialogId: int
    optimalLevel: int
    duration: float
    objectiveIds: List[int]
    rewardsIds: List[int]


Queststepsroot = List[QueststepsrootItem]
