# generated by datamodel-codegen:
#   filename:  ServersRoot.json
#   timestamp: 2025-06-08T12:34:14+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class ServersrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int
    commentId: str
    openingDate: float
    language: str
    populationId: int
    gameTypeId: int
    communityId: int
    restrictedToLanguages: List
    monoAccount: int
    illus: str


Serversroot = List[ServersrootItem]
