# generated by datamodel-codegen:
#   filename:  ServerLangsRoot.json
#   timestamp: 2025-06-08T12:34:05+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class ServerlangsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int
    langCode: str


Serverlangsroot = List[ServerlangsrootItem]
