# generated by datamodel-codegen:
#   filename:  ServerSeasonsRoot.json
#   timestamp: 2025-06-08T12:34:11+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class ServerseasonsrootItem(Struct, frozen=True, kw_only=True):
    uid: int
    nameId: str
    beginning: float
    closure: float
    resetDate: float
    flagObjectId: int


Serverseasonsroot = List[ServerseasonsrootItem]
