# generated by datamodel-codegen:
#   filename:  SkillNamesRoot.json
#   timestamp: 2025-06-08T12:34:20+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class SkillnamesrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int


Skillnamesroot = List[SkillnamesrootItem]
