# generated by datamodel-codegen:
#   filename:  SkinMappingsRoot.json
#   timestamp: 2025-06-08T12:34:23+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class SkinmappingsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    lowDefId: int


Skinmappingsroot = List[SkinmappingsrootItem]
