# generated by datamodel-codegen:
#   filename:  SmileyCategoriesRoot.json
#   timestamp: 2025-06-08T12:34:31+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class SmileycategoriesrootItem(Struct, frozen=True, kw_only=True):
    id: int
    order: int
    gfxId: str
    isFake: int


Smileycategoriesroot = List[SmileycategoriesrootItem]
