# generated by datamodel-codegen:
#   filename:  SmileysRoot.json
#   timestamp: 2025-06-08T12:34:37+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class SmileysrootItem(Struct, frozen=True, kw_only=True):
    id: int
    order: int
    gfxId: str
    forPlayers: int
    triggers: List[str]
    referenceId: int
    categoryId: int


Smileysroot = List[SmileysrootItem]
