# generated by datamodel-codegen:
#   filename:  SoundUiHookRoot.json
#   timestamp: 2025-06-08T12:34:51+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class SounduihookrootItem(Struct, frozen=True, kw_only=True):
    id: int
    name: str


Sounduihookroot = List[SounduihookrootItem]
