# generated by datamodel-codegen:
#   filename:  SpeakingItemsTriggersRoot.json
#   timestamp: 2025-06-08T12:35:01+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class SpeakingitemstriggersrootItem(Struct, frozen=True, kw_only=True):
    triggersId: int
    textIds: List[int]
    states: List[int]


Speakingitemstriggersroot = List[SpeakingitemstriggersrootItem]
