# generated by datamodel-codegen:
#   filename:  SpellBombsRoot.json
#   timestamp: 2025-06-08T12:35:04+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class SpellbombsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    chainReactionSpellId: int
    explodSpellId: int
    wallId: int
    instantSpellId: int
    comboCoeff: int


Spellbombsroot = List[SpellbombsrootItem]
