# generated by datamodel-codegen:
#   filename:  SpellConversionsRoot.json
#   timestamp: 2025-06-08T12:35:07+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class SpellconversionsrootItem(Struct, frozen=True, kw_only=True):
    oldSpellId: int
    newSpellId: int


Spellconversionsroot = List[SpellconversionsrootItem]
