# generated by datamodel-codegen:
#   filename:  SubhintsRoot.json
#   timestamp: 2025-06-08T12:35:43+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class SubhintsrootItem(Struct, frozen=True, kw_only=True):
    hintId: int
    hintParentUid: str
    hintAnchoredElement: str
    hintAnchor: int
    hintPositionX: int
    hintPositionY: int
    hintWidth: int
    hintHeight: int
    hintHighlightedElement: str
    hintOrder: int
    hintTooltipText: str
    hintTooltipPositionEnum: int
    hintTooltipUrl: str
    hintTooltipOffsetX: int
    hintTooltipOffsetY: int
    hintTooltipWidth: int
    hintCreationDate: float


Subhintsroot = List[SubhintsrootItem]
