# generated by datamodel-codegen:
#   filename:  SuperAreasRoot.json
#   timestamp: 2025-06-08T12:35:46+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class SuperareasrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int
    worldmapId: int
    hasWorldMap: int


Superareasroot = List[SuperareasrootItem]
