# generated by datamodel-codegen:
#   filename:  TaxCollectorFirstnamesRoot.json
#   timestamp: 2025-06-08T12:35:50+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class TaxcollectorfirstnamesrootItem(Struct, frozen=True, kw_only=True):
    id: int
    firstnameId: str


Taxcollectorfirstnamesroot = List[TaxcollectorfirstnamesrootItem]
