# generated by datamodel-codegen:
#   filename:  TextIconReferencesRoot.json
#   timestamp: 2025-06-08T12:35:56+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class TexticonreferencesrootItem(Struct, frozen=True, kw_only=True):
    id: int
    gfxId: str
    referenceKey: str


Texticonreferencesroot = List[TexticonreferencesrootItem]
