# generated by datamodel-codegen:
#   filename:  TitleCategoriesRoot.json
#   timestamp: 2025-06-08T12:36:02+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class TitlecategoriesrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int


Titlecategoriesroot = List[TitlecategoriesrootItem]
