# generated by datamodel-codegen:
#   filename:  WorldEventsRoot.json
#   timestamp: 2025-06-08T12:36:11+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class WorldeventsrootItem(Struct, frozen=True, kw_only=True):
    id: int
    nameId: int
    categoryId: int
    areas: List
    subareas: List[int]
    globalDrops: List[int]
    fightScenarios: List
    deletedObjects: List
    monsterHunterGroupsPerMap: int
    dungeonHunterGroupsPerMap: int
    preMsgId: int
    startMsgId: int
    endMsgId: int
    preMsgDelay: int
    scoreMsgTiming: int


Worldeventsroot = List[WorldeventsrootItem]
